### ISSUE TITLE
Error during init with ATC sensors (no encryption)

### ISSUE THREAD

**Issue by bneenb** [custom-components/ble_monitor#1021]
Hi, I collect the data of 3 ATC sensors with ble_monitor.
The sensors are set up to not use encryption. Also they worked well before the restart of Home Assistant.

Suddenly after a restart (I believe it was the first after setting the system up), I got the following error:

> Error setting up entry Bluetooth Low Energy Monitor for ble_monitor
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
>     result = await component.async_setup_entry(hass, self)
>   File "/config/custom_components/ble_monitor/__init__.py", line 407, in async_setup_entry
>     blemonitor.start()
>   File "/config/custom_components/ble_monitor/__init__.py", line 528, in start
>     self.dumpthread = HCIdump(
>   File "/config/custom_components/ble_monitor/__init__.py", line 610, in __init__
>     p_key = bytes.fromhex(device[CONF_DEVICE_ENCRYPTION_KEY].lower())
> ValueError: non-hexadecimal number found in fromhex() arg at position 0

I'm on version 9.2.0 if that matters.

(edit: wrong traceback, now its correct.)

**Comment by Ernst79** [comment]
Can you enable debug logging for ble monitor? And can you make sure there is no encryption key entered in your ble monitor device options?

**Comment by bneenb** [comment]
Thanks for the quick response.
Can you give me a hint, how to enable debug logging?

I tried adding this to my configuration.yaml:
```
logger:
  default: error
  logs:
    homeassistant.custom_components.ble_monitor: debug
```
but it didn't give me more logs. I also tried with "components" instead of "custom_components".

Also, where can I find the device configs?

Thank you for your support!

**Comment by bneenb** [comment]
Okay, I double checked and the ecryption key is empty for all devices. Even though the note in the input field says it should have a '-' if not used.

Now also the debug output worked:

```
2022-09-15 16:43:36.693 DEBUG (MainThread) [custom_components.ble_monitor.bt_helpers] Response(header=<event_code=CommandCompleteEvent, controller_idx=0, param_len=283>, event_frame=<command_opcode=ReadControllerInformation, status=Success>, cmd_response_frame=<address=00:E0:43:XX:XX:XX, bluetooth_version=10, manufacturer=93, supported_settings=114431, current_settings={Powered: True, Connectable: False, FastConnectable: False, Discoverable: False, Bondable: False, LinkLevelSecurity: False, SecureSimplePairing: True, BREDR: True, HighSpeed: False, LowEnergy: True, Advertising: False, SecureConnections: True, DebugKeys: False, Privacy: False, ControllerConfiguration: False, StaticAddress: False, PHYConfiguration: False, WidebandSpeech: False}, class_of_device=0, name=b'homeassistant', short_name=0>)
2022-09-15 16:43:37.093 DEBUG (MainThread) [custom_components.ble_monitor] Initializing BLE Monitor entry (config entry): <homeassistant.config_entries.ConfigEntry object at 0x7fd22391d080>
2022-09-15 16:43:37.094 DEBUG (MainThread) [custom_components.ble_monitor] async_setup_entry: domain {}
2022-09-15 16:43:37.095 DEBUG (MainThread) [custom_components.ble_monitor] HCI interface is [0]
2022-09-15 16:43:37.095 DEBUG (MainThread) [custom_components.ble_monitor] async_setup_entry: {'bt_interface': ['00:E0:43:81:41:03'], 'bt_auto_restart': True, 'active_scan': False, 'discovery': True, 'period': 60, 'use_median': False, 'decimals': 1, 'log_spikes': False, 'restore_state': False, 'report_unknown': 'ATC', 'devices': [{'uuid': '50765CB7-D9EA-4E21-99A4-FA8796XXXXXX', 'name': '50765CB7D9EA4E2199A4FA8796XXXXXX'}, {'mac': 'A4:C1:38:XX:XX:XX', 'name': 'ThermometerWoZi', 'encryption_key': '-', 'temperature_unit': '°C', 'decimals': 1, 'use_median': 'default', 'restore_state': 'default', 'reset_timer': 35, 'report_unknown': False, 'track_device': False, 'tracker_scan_interval': 20, 'consider_home': 180, 'delete device': False, 'uuid': ''}, {'mac': 'A4:C1:38:XX:XX:XX', 'name': 'ThermometerSchlaZi'}, {'mac': 'A4:C1:38:XX:XX:XX', 'name': 'ThermometerBad'}], 'is_flow': True, 'hci_interface': [0]}
2022-09-15 16:43:37.095 DEBUG (MainThread) [custom_components.ble_monitor] Spawning HCIdump thread
2022-09-15 16:43:37.095 DEBUG (MainThread) [custom_components.ble_monitor] HCIdump thread: Init
2022-09-15 16:43:37.098 INFO (MainThread) [custom_components.ble_monitor] Attention! Option report_unknown is enabled for ATC sensors, be ready for a huge output
2022-09-15 16:43:37.111 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Bluetooth Low Energy Monitor for ble_monitor
File "/config/custom_components/ble_monitor/__init__.py", line 407, in async_setup_entry
File "/config/custom_components/ble_monitor/__init__.py", line 528, in start
File "/config/custom_components/ble_monitor/__init__.py", line 610, in __init__
```

**Comment by Ernst79** [comment]
I see that the device `'A4:C1:38:XX:XX:XX', 'name': 'ThermometerWoZi' ` has `encryption_key ‘-‘` in the log. I think for some strange reason this isn’t changed back to empty (-) should remove the key. 

Can you delete this device entirely and re-add it after a restart?

**Comment by bneenb** [comment]
Thats odd... I have removed the device "ThermometerWoZi" by clicking 'configure' on the ble_monitor integration, then choosing the device, click 'send', tick 'Delete device', click 'send'.

Then the device is no longer in the list. After a restart of Home Assistant, the device still not in the devices list.
But the error is still the same and I can still see the device "ThermometerWoZi" in the log with the encryption_key '-'.

How can I completely remove it?

**Comment by bneenb** [comment]
After turning on automatic discovery again and adding the device that way, not manually, it worked again.
It seems like the error is gone now. Even after multiple restarts of HomeAssistant and the host system, it works normally.

Thank you very much for the support. Even though we didn't find out, why the encryption key was set to '-'.

Would it make sense to ignore encryption keys like this in the future?

**Comment by Ernst79** [comment]
Normally, "-" should be used to delete the encryption key, but somehow it kept stuck in your config. Not sure what happened. As this option is already there for quite some time and you are the first to notice this error, I assume it is some edge case. I'll keep an eye on similar issues in the future, if it happens again, I'll dig into it. But for now, I assume it was just bad luck.
