### ISSUE TITLE
Temperature sensor not working after 10.5.0 update

### ISSUE THREAD

**Issue by andker87** [custom-components/ble_monitor#1033]
as mentioned [here](https://github.com/custom-components/ble_monitor/issues/1031#issuecomment-1270393731), after 10.5.0 update

```
Error adding entities for domain sensor with platform ble_monitor
Error while setting up ble_monitor platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 691, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/ble_monitor/sensor.py", line 497, in async_added_to_hass
    self.state = TemperatureConverter.convert(
AttributeError: can't set attribute 'state'
```

humidity is working fine, temperature doesn't

**Comment by Ernst79** [comment]
fix is on its way, Had a small typo. Release will be finished in 10 minutes

**Comment by Ernst79** [comment]
10.5.1 has been release, which should fix the problem. Can take a few minutes to show up in HACS. Thanks for reporting.

**Comment by Kaibob2** [comment]
Everything back to normal. Thanks for the quick fix.
