### ISSUE TITLE
[Bug]: ble_parser/xiaomi 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by jinuxx** [custom-components/ble_monitor#1060]
### What happened?

I have the MJZNMSQ01YD (Xiaomi Door Lock Youth Edition), and ha is running in docker.

After ha restart, the ble lock status is unknow. And after unlock once, the status goes to unlock and never change. 

![image](https://user-images.githubusercontent.com/24599163/206175151-0c601e92-4e1f-47b0-a65e-b8611257b04f.png)

Maybe the ble lock status should be like this ? lock -> unlock -> lock again?

Relevant log is attached below.

### Sensor type

MJZNMSQ01YD (Xiaomi Door Lock Youth Edition).

### Relevant log output

```shell
2022-12-07 19:36:15.336 ERROR (Thread-2) [homeassistant] Error doing job: Fatal error: protocol.data_received() call failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 868, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.10/site-packages/aioblescan/aioblescan.py", line 1855, in data_received
    self.process(packet)
  File "/config/custom_components/ble_monitor/__init__.py", line 662, in process_hci_events
    sensor_msg, tracker_msg = self.ble_parser.parse_raw_data(data)
  File "/config/custom_components/ble_monitor/ble_parser/__init__.py", line 152, in parse_raw_data
    sensor_data, tracker_data = self.parse_advertisement(
  File "/config/custom_components/ble_monitor/ble_parser/__init__.py", line 220, in parse_advertisement
    sensor_data = parse_xiaomi(self, service_data, mac, rssi)
  File "/config/custom_components/ble_monitor/ble_parser/xiaomi.py", line 1092, in parse_xiaomi
    result.update(resfunc(dobject, device_type))
TypeError: 'NoneType' object is not iterable
2022-12-07 19:38:15.460 ERROR (Thread-2) [homeassistant] Error doing job: Fatal error: protocol.data_received() call failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 868, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.10/site-packages/aioblescan/aioblescan.py", line 1855, in data_received
    self.process(packet)
  File "/config/custom_components/ble_monitor/__init__.py", line 662, in process_hci_events
    sensor_msg, tracker_msg = self.ble_parser.parse_raw_data(data)
  File "/config/custom_components/ble_monitor/ble_parser/__init__.py", line 152, in parse_raw_data
    sensor_data, tracker_data = self.parse_advertisement(
  File "/config/custom_components/ble_monitor/ble_parser/__init__.py", line 220, in parse_advertisement
    sensor_data = parse_xiaomi(self, service_data, mac, rssi)
  File "/config/custom_components/ble_monitor/ble_parser/xiaomi.py", line 1092, in parse_xiaomi
    result.update(resfunc(dobject, device_type))
TypeError: 'NoneType' object is not iterable
2022-12-07 19:40:15.598 ERROR (Thread-2) [homeassistant] Error doing job: Fatal error: protocol.data_received() call failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 868, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.10/site-packages/aioblescan/aioblescan.py", line 1855, in data_received
    self.process(packet)
  File "/config/custom_components/ble_monitor/__init__.py", line 662, in process_hci_events
    sensor_msg, tracker_msg = self.ble_parser.parse_raw_data(data)
  File "/config/custom_components/ble_monitor/ble_parser/__init__.py", line 152, in parse_raw_data
    sensor_data, tracker_data = self.parse_advertisement(
  File "/config/custom_components/ble_monitor/ble_parser/__init__.py", line 220, in parse_advertisement
    sensor_data = parse_xiaomi(self, service_data, mac, rssi)
  File "/config/custom_components/ble_monitor/ble_parser/xiaomi.py", line 1092, in parse_xiaomi
    _LOGGER.info("%s, UNKNOWN dataobject in payload! Adv: %s", sinfo, data.hex())
TypeError: 'NoneType' object is not iterable
```

**Comment by Ernst79** [comment]
Will be fixed in the next release.
