### ISSUE TITLE
has no attribute 'AF_BLUETOOTH'

### ISSUE THREAD

**Issue by oomichalekoo** [custom-components/ble_monitor#1070]
### What happened?

How I can  dissable this error?

`Ten błąd pochodzi z niestandardowej integracji.

Logger: root
Source: custom_components/ble_monitor/__init__.py:597
Integration: Passive BLE monitor (documentation, issues)
First occurred: 23:16:17 (10 occurrences)
Last logged: 23:25:21

Uncaught thread exception
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/data/data/com.termux/files/home/AIS/custom_components/ble_monitor/__init__.py", line 597, in run
    mysocket[hci] = aiobs.create_bt_socket(hci)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/aioblescan/aioblescan.py", line 1691, in create_bt_socket
    family=socket.AF_BLUETOOTH, type=socket.SOCK_RAW, proto=socket.BTPROTO_HCI
AttributeError: module 'socket' has no attribute 'AF_BLUETOOTH'
`

**Comment by Ernst79** [comment]
Please check the FAQ in the documentation. This error (and solution ) is described  the faq.

**Comment by oomichalekoo** [comment]
I dont have bluetooth i am just using esp32

śr., 14 gru 2022, 23:30 użytkownik Ernst Klamer ***@***.***>
napisał:

**Comment by Ernst79** [comment]
I think you need to disable the bluetooth interface (as you don't have it), with:

```
ble_monitor:
  bt_interface: "disable"
```

**Comment by oomichalekoo** [comment]
Invalid config for [ble_monitor]: value disable does not match regular
expression (?i)^(?:[0-9A-F]{2}[:]){5}(?:[0-9A-F]{2})$ @
data['ble_monitor']['bt_interface'][0]. Got 'd'. (See
/data/data/com.termux/files/home/AIS/configuration.yaml, line 43).

ble_monitor:
  bt_interface: disable
  discovery: false
  restore_state: true
  decimals: 1
  period: 60
  devices:
    - name: iNode
      mac: D0:60:58:78:07:C1

dont work i have error
Invalid config for [ble_monitor]: value disable does not match regular
expression (?i)^(?:[0-9A-F]{2}[:]){5}(?:[0-9A-F]{2})$ @
data['ble_monitor']['bt_interface'][0]. Got 'd'. (See
/data/data/com.termux/files/home/AIS/configuration.yaml, line 43).

niedz., 18 gru 2022 o 10:21 Ernst Klamer ***@***.***>
napisał(a):

**Comment by Ernst79** [comment]
You forgot the quote marks `" "` around disable.

```yaml
ble_monitor:
  bt_interface: "disable"
```

**Comment by oomichalekoo** [comment]
Invalid config for [ble_monitor]: value disable does not match regular
expression (?i)^(?:[0-9A-F]{2}[:]){5}(?:[0-9A-F]{2})$ @
data['ble_monitor']['bt_interface'][0]. Got 'd'. (See
/data/data/com.termux/files/home/AIS/configuration.yaml, line 43).
still dont works

niedz., 18 gru 2022 o 10:39 Ernst Klamer ***@***.***>
napisał(a):

**Comment by oomichalekoo** [comment]
ble_monitor:
  bt_interface: "disable"
  discovery: false
  restore_state: true
  decimals: 1
  period: 60
  devices:
    - name: iNode
      mac: D0:54:18:58:07:C1

niedz., 18 gru 2022 o 10:44 Michał ***@***.***> napisał(a):

**Comment by Ernst79** [comment]
Are you 100% sure. It still says it sees a `d` (Got 'd'.). It should see a ". 

Try it with only 

```
ble_monitor:
  bt_interface: "disable"
``` 

first, and later, add the rest.

**Comment by oomichalekoo** [comment]
Od i tryb only this Inode energy stop working

niedz., 18 gru 2022, 10:51 użytkownik Ernst Klamer ***@***.***>
napisał:

**Comment by Ernst79** [comment]
So, no errors now, 

Next, add the full configuration back now. 

```yaml
ble_monitor:
  bt_interface: "disable"
  discovery: false
  restore_state: true
  decimals: 1
  period: 60
  devices:
    - name: iNode
      mac: D0:54:18:58:07:C1
```

**Comment by oomichalekoo** [comment]
Ok i wilk try

niedz., 18 gru 2022, 10:56 użytkownik Ernst Klamer ***@***.***>
napisał:

**Comment by oomichalekoo** [comment]
still problem
i add

ble_monitor:
  bt_interface: "disable"

restart HA

add

  discovery: false
  restore_state: true
  decimals: 1
  period: 60
  devices:
    - name: iNode
      mac: D0:54:48:58:07:C1

and again get error

Invalid config for [ble_monitor]: value disable does not match regular
expression (?i)^(?:[0-9A-F]{2}[:]){5}(?:[0-9A-F]{2})$ @
data['ble_monitor']['bt_interface'][0]. Got 'd'. (See
/data/data/com.termux/files/home/AIS/configuration.yaml, line 43).



niedz., 18 gru 2022 o 11:08 Michał ***@***.***> napisał(a):

**Comment by oomichalekoo** [comment]
my version ble is 6.4

niedz., 18 gru 2022 o 11:31 Michał ***@***.***> napisał(a):

**Comment by Ernst79** [comment]
Version 6.4 of BLE monitor. That is really old. we are at 10.9.2 at the moment. 

Anyway. you found a bug, I guess. I checked the code and I think it expects a list. 
Try the following:

```yaml
ble_monitor:
  bt_interface:
    - "disable"
```

**Comment by oomichalekoo** [comment]
still problem but work with this

ble_monitor:
  bt_interface:
    - "disable"
  discovery: false
  restore_state: true
  decimals: 1
  period: 60
  devices:
    - name: iNode
      mac: D0:F0:1f:ff:ff:C1


Logger: root
Source: custom_components/ble_monitor/__init__.py:597
Integration: Passive BLE monitor (documentation, issues)
First occurred: 12:05:35 (1 occurrences)
Last logged: 12:05:35

Uncaught thread exception
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/threading.py", line
1016, in _bootstrap_inner
    self.run()
  File
"/data/data/com.termux/files/home/AIS/custom_components/ble_monitor/__init__.py",
line 597, in run
    mysocket[hci] = aiobs.create_bt_socket(hci)
  File
"/data/data/com.termux/files/usr/lib/python3.10/site-packages/aioblescan/aioblescan.py",
line 1691, in create_bt_socket
    family=socket.AF_BLUETOOTH, type=socket.SOCK_RAW,
proto=socket.BTPROTO_HCI
AttributeError: module 'socket' has no attribute 'AF_BLUETOOTH'

niedz., 18 gru 2022 o 11:40 Ernst Klamer ***@***.***>
napisał(a):

**Comment by oomichalekoo** [comment]
now i check yaml and again get this error
Invalid config for [ble_monitor]: value disable does not match regular
expression (?i)^(?:[0-9A-F]{2}[:]){5}(?:[0-9A-F]{2})$ @
data['ble_monitor']['bt_interface'][0]. Got 'disable'. (See
/data/data/com.termux/files/home/AIS/configuration.yaml, line 42).

niedz., 18 gru 2022 o 12:06 Michał ***@***.***> napisał(a):

**Comment by Ernst79** [comment]
hmm, sorry. I will try to create a yaml configuration myself after coming week to see what is wrong. 

The only thing you could try is to not use yaml configuration, but use the UI to setup BLE monitor (just delete YAML configuration, and restart HA). You should than be able to configure BLE monitor from the UI. Make sure you disable the Bluetooth Interface. 

I will get back to you after the coming week to see what is wrong with YAML

**Comment by oomichalekoo** [comment]
Ok i wait for your answer

niedz., 18 gru 2022, 12:18 użytkownik Ernst Klamer ***@***.***>
napisał:

**Comment by oomichalekoo** [comment]
*if i use gui i have bluetooth hci_interface: "00"00"00"00"00 <- mac adres*
*i try everything and still have error*

niedz., 18 gru 2022 o 12:27 Michał ***@***.***> napisał(a):

**Comment by oomichalekoo** [comment]
Hi are you check this configuration to disable BT

niedz., 18 gru 2022 o 21:53 Michał ***@***.***> napisał(a):

**Comment by oomichalekoo** [comment]
Or how i can dissable logs error BT

pon., 2 sty 2023, 13:37 użytkownik Michał ***@***.***> napisał:

**Comment by oomichalekoo** [comment]
Ble monitor im version 6.4 dont have dissable BT in gui.Other wersjom font
work for me idk why i have HA  2022.13.8

pon., 2 sty 2023, 14:01 użytkownik Michał ***@***.***> napisał:

**Comment by oomichalekoo** [comment]
Hi i instal version 7.5 dissable bluetooth and nie working But version 6.4
report inode every 1 minutę stats in version i have report randomly i have
period 60 , reset timer 10 period inode 10 away home 1800 aby sugestion to
raport inode every 1 minute

pon., 2 sty 2023, 14:44 użytkownik Michał ***@***.***> napisał:
