### ISSUE TITLE
[Bug]: ERROR (Thread-3) [homeassistant] Error doing job: Fatal error: protocol.data_received() call failed.

### ISSUE THREAD

**Issue by dugurs** [custom-components/ble_monitor#1177]
### What happened?

The ble sensor I am using is
LYWSD03MMC * 3 (ATC custom), CGG1 * 1, Mi Scale V2 * 1.
If you are using NUC proxmox haos, all are using the latest version.
The Bluetooth adapter is using Zexmte 100M USB BT5.1.
The error is occurring endlessly.
The sensor being used shows the value normally.

### Relevant log output

```shell
2023-05-18 15:44:44.156 ERROR (Thread-3) [homeassistant] Error doing job: Fatal error: protocol.data_received() call failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 876, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.10/site-packages/aioblescan/aioblescan.py", line 1855, in data_received
    self.process(packet)
  File "/config/custom_components/ble_monitor/__init__.py", line 636, in process_hci_events
    sensor_msg, tracker_msg = self.ble_parser.parse_raw_data(data)
  File "/config/custom_components/ble_monitor/ble_parser/__init__.py", line 137, in parse_raw_data
    shortened_local_name = adstruct[2:].decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
2023-05-18 15:45:12.096 ERROR (Thread-3) [homeassistant] Error doing job: Fatal error: protocol.data_received() call failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 876, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.10/site-packages/aioblescan/aioblescan.py", line 1855, in data_received
    self.process(packet)
  File "/config/custom_components/ble_monitor/__init__.py", line 636, in process_hci_events
    sensor_msg, tracker_msg = self.ble_parser.parse_raw_data(data)
  File "/config/custom_components/ble_monitor/ble_parser/__init__.py", line 137, in parse_raw_data
    shortened_local_name = adstruct[2:].decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by Ernst79** [comment]
It looks like this is an issue in [aioblescan](https://github.com/frawau/aioblescan). Aioblescan is the parser that receives the raw ble data and makes it readable to BLE monitor. Can you create an issue in the aioblescan repo?

**Comment by dugurs** [comment]
[aioblescan-3.log](https://github.com/custom-components/ble_monitor/files/11778020/aioblescan-3.log)
[aioblescan-2.log](https://github.com/custom-components/ble_monitor/files/11778021/aioblescan-2.log)
[home-assistant_ble_monitor_2023-06-17T05-30-44.646Z.log](https://github.com/custom-components/ble_monitor/files/11778022/home-assistant_ble_monitor_2023-06-17T05-30-44.646Z.log)

mi scale 2
MAC: 0C:95:41:AC:71:E1
UUID: 18:1B

I don't know if it's a coincidence.
When I started debugging in the integration component, I started to read the oath well.

Normal packets are recorded in the debug log.

Thank you for your hard work.

**Comment by dugurs** [comment]
I modified the source a bit to enable debug log of raw data. Please check.

```
2023-06-20 11:41:55.520 DEBUG (Thread-3) [custom_components.ble_monitor] raw data: b'\x04>9\r\x01\x13\x00\x00\x05\x02\x99_\x16\xb8\x01\x00\xff\x7f\x9a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1f\x02\x01\x05\x08\xff\xc4\x00\xb7\x92\x15\x16\x80\x03\x03\xb9\xfe\x08\x1b\x00\x05\x02\x99_\x16\xb8\x02\n\xe8\x02\x08\xff'
2023-06-20 11:41:55.520 DEBUG (Thread-3) [custom_components.ble_monitor.ble_parser] adstruct: b'\x02\x01\x05'
2023-06-20 11:41:55.520 DEBUG (Thread-3) [custom_components.ble_monitor.ble_parser] adstruct: b'\x08\xff\xc4\x00\xb7\x92\x15\x16\x80'
2023-06-20 11:41:55.520 DEBUG (Thread-3) [custom_components.ble_monitor.ble_parser] adstruct: b'\x03\x03\xb9\xfe'
2023-06-20 11:41:55.520 DEBUG (Thread-3) [custom_components.ble_monitor.ble_parser] adstruct: b'\x08\x1b\x00\x05\x02\x99_\x16\xb8'
2023-06-20 11:41:55.520 DEBUG (Thread-3) [custom_components.ble_monitor.ble_parser] adstruct: b'\x02\n\xe8'
2023-06-20 11:41:55.520 DEBUG (Thread-3) [custom_components.ble_monitor.ble_parser] adstruct: b'\x02\x08\xff'
2023-06-20 11:41:55.521 ERROR (Thread-3) [homeassistant] Error doing job: Fatal error: protocol.data_received() call failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 1009, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.11/site-packages/aioblescan/aioblescan.py", line 1855, in data_received
    self.process(packet)
  File "/config/custom_components/ble_monitor/__init__.py", line 587, in process_hci_events
    sensor_msg, tracker_msg = self.ble_parser.parse_raw_data(data)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ble_monitor/ble_parser/__init__.py", line 139, in parse_raw_data
    shortened_local_name = adstruct[2:].decode("utf-8")
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
2023-06-20 11:41:58.119 DEBUG (Thread-3) [custom_components.ble_monitor] raw data: b'\x04>9\r\x01\x13\x00\x00\x05\x02\x99_\x16\xb8\x01\x00\xff\x7f\x9a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1f\x02\x01\x05\x08\xff\xc4\x00\xb7\x92\x15\x16\x80\x03\x03\xb9\xfe\x08\x1b\x00\x05\x02\x99_\x16\xb8\x02\n\xe8\x02\x08\xff'
2023-06-20 11:41:58.119 DEBUG (Thread-3) [custom_components.ble_monitor.ble_parser] adstruct: b'\x02\x01\x05'
2023-06-20 11:41:58.119 DEBUG (Thread-3) [custom_components.ble_monitor.ble_parser] adstruct: b'\x08\xff\xc4\x00\xb7\x92\x15\x16\x80'
2023-06-20 11:41:58.119 DEBUG (Thread-3) [custom_components.ble_monitor.ble_parser] adstruct: b'\x03\x03\xb9\xfe'
2023-06-20 11:41:58.119 DEBUG (Thread-3) [custom_components.ble_monitor.ble_parser] adstruct: b'\x08\x1b\x00\x05\x02\x99_\x16\xb8'
2023-06-20 11:41:58.119 DEBUG (Thread-3) [custom_components.ble_monitor.ble_parser] adstruct: b'\x02\n\xe8'
2023-06-20 11:41:58.119 DEBUG (Thread-3) [custom_components.ble_monitor.ble_parser] adstruct: b'\x02\x08\xff'
2023-06-20 11:41:58.119 ERROR (Thread-3) [homeassistant] Error doing job: Fatal error: protocol.data_received() call failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 1009, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.11/site-packages/aioblescan/aioblescan.py", line 1855, in data_received
    self.process(packet)
  File "/config/custom_components/ble_monitor/__init__.py", line 587, in process_hci_events
    sensor_msg, tracker_msg = self.ble_parser.parse_raw_data(data)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ble_monitor/ble_parser/__init__.py", line 139, in parse_raw_data
    shortened_local_name = adstruct[2:].decode("utf-8")
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
2023-06-20 11:42:17.256 DEBUG (Thread-3) [custom_components.ble_monitor] raw data: b'\x04>9\r\x01\x13\x00\x00\x05\x02\x99_\x16\xb8\x01\x00\xff\x7f\x98\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1f\x02\x01\x05\x08\xff\xc4\x00\xb7\x92\x15\x16\x80\x03\x03\xb9\xfe\x08\x1b\x00\x05\x02\x99_\x16\xb8\x02\n\xe8\x02\x08\xff'
2023-06-20 11:42:17.256 DEBUG (Thread-3) [custom_components.ble_monitor.ble_parser] adstruct: b'\x02\x01\x05'
2023-06-20 11:42:17.256 DEBUG (Thread-3) [custom_components.ble_monitor.ble_parser] adstruct: b'\x08\xff\xc4\x00\xb7\x92\x15\x16\x80'
2023-06-20 11:42:17.256 DEBUG (Thread-3) [custom_components.ble_monitor.ble_parser] adstruct: b'\x03\x03\xb9\xfe'
2023-06-20 11:42:17.256 DEBUG (Thread-3) [custom_components.ble_monitor.ble_parser] adstruct: b'\x08\x1b\x00\x05\x02\x99_\x16\xb8'
2023-06-20 11:42:17.256 DEBUG (Thread-3) [custom_components.ble_monitor.ble_parser] adstruct: b'\x02\n\xe8'
2023-06-20 11:42:17.256 DEBUG (Thread-3) [custom_components.ble_monitor.ble_parser] adstruct: b'\x02\x08\xff'
2023-06-20 11:42:17.256 ERROR (Thread-3) [homeassistant] Error doing job: Fatal error: protocol.data_received() call failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 1009, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.11/site-packages/aioblescan/aioblescan.py", line 1855, in data_received
    self.process(packet)
  File "/config/custom_components/ble_monitor/__init__.py", line 587, in process_hci_events
    sensor_msg, tracker_msg = self.ble_parser.parse_raw_data(data)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ble_monitor/ble_parser/__init__.py", line 139, in parse_raw_data
    shortened_local_name = adstruct[2:].decode("utf-8")
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
2023-06-20 11:42:44.005 DEBUG (Thread-3) [custom_components.ble_monitor] raw data: b'\x04>9\r\x01\x13\x00\x00\x05\x02\x99_\x16\xb8\x01\x00\xff\x7f\x9a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1f\x02\x01\x05\x08\xff\xc4\x00\xb7\x92\x15\x16\x80\x03\x03\xb9\xfe\x08\x1b\x00\x05\x02\x99_\x16\xb8\x02\n\xe8\x02\x08\xff'
2023-06-20 11:42:44.005 DEBUG (Thread-3) [custom_components.ble_monitor.ble_parser] adstruct: b'\x02\x01\x05'
2023-06-20 11:42:44.006 DEBUG (Thread-3) [custom_components.ble_monitor.ble_parser] adstruct: b'\x08\xff\xc4\x00\xb7\x92\x15\x16\x80'
2023-06-20 11:42:44.006 DEBUG (Thread-3) [custom_components.ble_monitor.ble_parser] adstruct: b'\x03\x03\xb9\xfe'
2023-06-20 11:42:44.006 DEBUG (Thread-3) [custom_components.ble_monitor.ble_parser] adstruct: b'\x08\x1b\x00\x05\x02\x99_\x16\xb8'
2023-06-20 11:42:44.006 DEBUG (Thread-3) [custom_components.ble_monitor.ble_parser] adstruct: b'\x02\n\xe8'
2023-06-20 11:42:44.006 DEBUG (Thread-3) [custom_components.ble_monitor.ble_parser] adstruct: b'\x02\x08\xff'
2023-06-20 11:42:44.006 ERROR (Thread-3) [homeassistant] Error doing job: Fatal error: protocol.data_received() call failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 1009, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.11/site-packages/aioblescan/aioblescan.py", line 1855, in data_received
    self.process(packet)
  File "/config/custom_components/ble_monitor/__init__.py", line 587, in process_hci_events
    sensor_msg, tracker_msg = self.ble_parser.parse_raw_data(data)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ble_monitor/ble_parser/__init__.py", line 139, in parse_raw_data
    shortened_local_name = adstruct[2:].decode("utf-8")
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
2023-06-20 11:42:58.669 DEBUG (Thread-3) [custom_components.ble_monitor] raw data: b'\x04>T\r\x02\x13\x00\x00\xb7"w8\xc1\xa4\x01\x00\xff\x7f\xb8\x00\x00\x00\x00\x00\x00\x00\x00\x00\x16\x02\x01\x06\x12\x16\x1a\x18\xb7"w8\xc1\xa4\xba\n~\x13\xa1\x0bd\xb6\x04\x1b\x00\x00\xb7"w8\xc1\xa4\x01\x00\xff\x7f\xb8\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0c\x0b\tATC_7722B7'
2023-06-20 11:42:59.166 DEBUG (Thread-3) [custom_components.ble_monitor] raw data: b'\x04>9\r\x01\x13\x00\x00\x05\x02\x99_\x16\xb8\x01\x00\xff\x7f\x98\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1f\x02\x01\x05\x08\xff\xc4\x00\xb7\x92\x15\x16\x80\x03\x03\xb9\xfe\x08\x1b\x00\x05\x02\x99_\x16\xb8\x02\n\xe8\x02\x08\xff'
2023-06-20 11:42:59.167 DEBUG (Thread-3) [custom_components.ble_monitor.ble_parser] adstruct: b'\x02\x01\x05'
2023-06-20 11:42:59.167 DEBUG (Thread-3) [custom_components.ble_monitor.ble_parser] adstruct: b'\x08\xff\xc4\x00\xb7\x92\x15\x16\x80'
2023-06-20 11:42:59.167 DEBUG (Thread-3) [custom_components.ble_monitor.ble_parser] adstruct: b'\x03\x03\xb9\xfe'
2023-06-20 11:42:59.167 DEBUG (Thread-3) [custom_components.ble_monitor.ble_parser] adstruct: b'\x08\x1b\x00\x05\x02\x99_\x16\xb8'
2023-06-20 11:42:59.167 DEBUG (Thread-3) [custom_components.ble_monitor.ble_parser] adstruct: b'\x02\n\xe8'
2023-06-20 11:42:59.167 DEBUG (Thread-3) [custom_components.ble_monitor.ble_parser] adstruct: b'\x02\x08\xff'
2023-06-20 11:42:59.167 ERROR (Thread-3) [homeassistant] Error doing job: Fatal error: protocol.data_received() call failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 1009, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.11/site-packages/aioblescan/aioblescan.py", line 1855, in data_received
    self.process(packet)
  File "/config/custom_components/ble_monitor/__init__.py", line 587, in process_hci_events
    sensor_msg, tracker_msg = self.ble_parser.parse_raw_data(data)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ble_monitor/ble_parser/__init__.py", line 139, in parse_raw_data
    shortened_local_name = adstruct[2:].decode("utf-8")
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by dugurs** [comment]
I found the cause.
An error occurred when the xiaomi-fp1 presence detection sensor was placed near the miscale weight,
Leaving miscale and fp1 away, the error was reduced or gone.
It seems that fp1 mmwave interfered with or modulated Bluetooth propagation.
