### ISSUE TITLE
[Bug]: Unexpected exception importing component custom_components.ble_monitor

### ISSUE THREAD

**Issue by rkononov** [custom-components/ble_monitor#1180]
### What happened?

ble_monitor cannot start after update, precision values aren't used anywhere.

### Sensor type

Amazfit scale

### Relevant log output

```shell
Logger: homeassistant.loader
Source: custom_components/ble_monitor/const.py:361
Integration: ble_monitor (documentation, issues)
First occurred: 9:29:27 PM (1 occurrences)
Last logged: 9:29:27 PM

Unexpected exception importing component custom_components.ble_monitor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 725, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/ble_monitor/__init__.py", line 30, in <module>
    from .const import (
  File "/config/custom_components/ble_monitor/const.py", line 361, in <module>
    BLEMonitorSensorEntityDescription(
TypeError: BLEMonitorSensorEntityDescription.__init__() got an unexpected keyword argument 'suggested_display_precision'
```

**Comment by Ernst79** [comment]
Most likely you are running an outdated Home Assistant version. Updating HA should fix this. If you don’t want to update now, downgrade BLE monitor to 11.x.x.

**Comment by rkononov** [comment]
Updated, it works, thank you! (was using :stable tag for the HASS image, had to switch to :latest)
