### ISSUE TITLE
[Bug]: Error doing job: Fatal error: protocol.data_received() call failed. when trying to log data for new sensor request.

### ISSUE THREAD

**Issue by phioschaos** [custom-components/ble_monitor#1186]
### What happened?

Following the instructions to get the BLE advertisements for a new sensor (Govee H5106) but the log file did not have any BLE advertisement messages. Instead, I periodically got an error message in the parser.

Home Assistant 2023.5.3
Passive BLE Monitor 12.0.0

### Sensor type

Govee H5106

### Relevant log output

```shell
2023-06-04 06:58:05.221 INFO (Thread-11) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID c53832314b99: service data: []manufacturer specific data: [b'\t\xff\x01\x00\x01\x01\r\x7f\x8d\x1c']local name: GVH5106_4B99UUID16: 35052,UUID128: None
2023-06-04 06:58:05.429 INFO (Thread-11) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID c53832314b99: service data: []manufacturer specific data: [b'\t\xff\x01\x00\x01\x01\r\x7f\x8d\x1c']local name: GVH5106_4B99UUID16: 35052,UUID128: None
2023-06-04 06:58:05.631 INFO (Thread-11) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID c53832314b99: service data: []manufacturer specific data: [b'\t\xff\x01\x00\x01\x01\r\x7f\x8d\x1c']local name: GVH5106_4B99UUID16: 35052,UUID128: None
2023-06-04 06:58:05.772 ERROR (Thread-11) [homeassistant] Error doing job: Fatal error: protocol.data_received() call failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 876, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.10/site-packages/aioblescan/aioblescan.py", line 1855, in data_received
    self.process(packet)
  File "/config/custom_components/ble_monitor/__init__.py", line 636, in process_hci_events
    sensor_msg, tracker_msg = self.ble_parser.parse_raw_data(data)
  File "/config/custom_components/ble_monitor/ble_parser/__init__.py", line 156, in parse_raw_data
    sensor_data, tracker_data = self.parse_advertisement(
  File "/config/custom_components/ble_monitor/ble_parser/__init__.py", line 245, in parse_advertisement
    sensor_data = parse_ruuvitag(self, service_data, mac, rssi)
  File "/config/custom_components/ble_monitor/ble_parser/ruuvitag.py", line 39, in parse_ruuvitag
    (version, humi, temp, frac, pres) = unpack(">BBbBH", decoded)
struct.error: unpack requires a buffer of 6 bytes
```

**Comment by phioschaos** [comment]
The device is incorrectly recognized as H5101/H5102/H5177
