### ISSUE TITLE
[Bug]: {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by GuidoKuo** [custom-components/ble_monitor#1214]
### What happened?

version:
homeassistant:2023.1.7
ble_monitor:12.3.2

when "Click on Add Integration in the bottom right corner and search for Passive BLE Monitor to install" happend this bug.

how to solved?

### Relevant log output

```shell
2023-07-26 23:16:30.183 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.ble_monitor.config_flow
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/loader.py", line 744, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 761, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 883, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/config/custom_components/ble_monitor/__init__.py", line 23, in <module>
from .const import (AES128KEY24_REGEX, AES128KEY32_REGEX,
File "/config/custom_components/ble_monitor/const.py", line 358, in <module>
BLEMonitorSensorEntityDescription(
TypeError: BLEMonitorSensorEntityDescription.__init__() got an unexpected keyword argument 'suggested_display_precision'
2023-07-26 23:16:30.185 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration ble_monitor: Exception importing custom_components.ble_monitor.config_flow
```

**Comment by Ernst79** [comment]
Your Home Assistant version is too old. Either use ble_monitor <= `11.11.1` or upgrade your Home Assistant.

**Comment by GuidoKuo** [comment]
good thanks

**Comment by ldwnt** [comment]
> Your Home Assistant version is too old. Either use ble_monitor <= `11.11.1` or upgrade your Home Assistant.

My HA core's version is 2024.10.4 and I get the same error when trying to configure ble monitor 12.19.0. What versions of HA core are compatible with ble monitor 12.19.0?

**Comment by Ernst79** [comment]
That should work, did you try a full system restart? Power off, power on?
