### ISSUE TITLE
Can't load components.

### ISSUE THREAD

**Issue by jerry-ch-issue** [custom-components/ble_monitor#1216]
### What happened?

Can't load components. 

### Relevant log output

```shell
ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.ble_monitor.config_flow
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 744, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 761, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/ble_monitor/__init__.py", line 23, in <module>
    from .const import (AES128KEY24_REGEX, AES128KEY32_REGEX,
  File "/home/homeassistant/.homeassistant/custom_components/ble_monitor/const.py", line 358, in <module>
    BLEMonitorSensorEntityDescription(
TypeError: __init__() got an unexpected keyword argument 'suggested_display_precision'
```

**Comment by Ernst79** [comment]
Your Home Assistant version is too old. Either use ble_monitor <= 11.11.1 or upgrade your Home Assistant.

**Comment by jerry-ch-issue** [comment]
> Your Home Assistant version is too old. Either use ble_monitor <= 11.11.1 or upgrade your Home Assistant.

Thanks for your reply and your excellent work. Because of python's version ( My OS is raspiberry pi, and I don't enable backports) , so I have to download component(v11.11.1) Manually. Now it works just as well as before. 

I remember not being able to upgrade this, but HACS always kept it in the need to upgrade menu, and when I installed it manually, it disappeared in HACS.
