### ISSUE TITLE
[Bug]: Exception importing custom_components.ble_monitor

### ISSUE THREAD

**Issue by ryanmaule** [custom-components/ble_monitor#1233]
### What happened?

Started getting 2 errors this week relating to "valid Events".

### Relevant log output

```shell
Error #1:
Logger: homeassistant.setup
Source: loader.py:826
First occurred: September 6, 2023 at 5:37:47 PM (1 occurrences)
Last logged: September 6, 2023 at 5:37:47 PM

Setup failed for custom integration ble_monitor: Unable to import component: Exception importing custom_components.ble_monitor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 818, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/ble_monitor/__init__.py", line 21, in <module>
    from .bt_helpers import (BT_INTERFACES, BT_MULTI_SELECT, DEFAULT_BT_INTERFACE,
  File "/config/custom_components/ble_monitor/bt_helpers.py", line 162, in <module>
    BT_INTERFACES = hci_get_mac([0, 1, 2, 3])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ble_monitor/bt_helpers.py", line 88, in hci_get_mac
    btctl = MGMTBluetoothCtl()
            ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ble_monitor/bt_helpers.py", line 35, in __init__
    idxdata = btmgmt_sync.send('ReadControllerIndexList', None)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/btsocket/btmgmt_sync.py", line 28, in send
    data = btmgmt_protocol.reader(raw_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/btsocket/btmgmt_protocol.py", line 1035, in reader
    evt_params = header.decode(pckt)
                 ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/btsocket/btmgmt_protocol.py", line 227, in decode
    data_type.decode(pkt[pointer:pointer + param.width])
  File "/usr/local/lib/python3.11/site-packages/btsocket/btmgmt_protocol.py", line 99, in decode
    self.value = Events(int.from_bytes(data, byteorder='little'))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 712, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 1128, in __new__
    raise ve_exc
ValueError: 47 is not a valid Events

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 826, in get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.ble_monitor

Error #2:
This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/ble_monitor/bt_helpers.py:35
Integration: ble_monitor (documentation, issues)
First occurred: September 6, 2023 at 5:37:47 PM (1 occurrences)
Last logged: September 6, 2023 at 5:37:47 PM

Unexpected exception importing component custom_components.ble_monitor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 818, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/ble_monitor/__init__.py", line 21, in <module>
    from .bt_helpers import (BT_INTERFACES, BT_MULTI_SELECT, DEFAULT_BT_INTERFACE,
  File "/config/custom_components/ble_monitor/bt_helpers.py", line 162, in <module>
    BT_INTERFACES = hci_get_mac([0, 1, 2, 3])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ble_monitor/bt_helpers.py", line 88, in hci_get_mac
    btctl = MGMTBluetoothCtl()
            ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ble_monitor/bt_helpers.py", line 35, in __init__
    idxdata = btmgmt_sync.send('ReadControllerIndexList', None)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/btsocket/btmgmt_sync.py", line 28, in send
    data = btmgmt_protocol.reader(raw_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/btsocket/btmgmt_protocol.py", line 1035, in reader
    evt_params = header.decode(pckt)
                 ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/btsocket/btmgmt_protocol.py", line 227, in decode
    data_type.decode(pkt[pointer:pointer + param.width])
  File "/usr/local/lib/python3.11/site-packages/btsocket/btmgmt_protocol.py", line 99, in decode
    self.value = Events(int.from_bytes(data, byteorder='little'))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 712, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 1128, in __new__
    raise ve_exc
ValueError: 47 is not a valid Events
```

**Comment by ryanmaule** [comment]
This error was resolved by going to HACS and redownloading the Integration.
