### ISSUE TITLE
[Bug]: The component cannot run in HA

### ISSUE THREAD

**Issue by junskr** [custom-components/ble_monitor#1235]
### What happened?

I have been using this component for a very long time. I am always grateful.
However, one day, an error suddenly appears saying that the component cannot be executed.
I tried rebooting the system, deleting the component, and reinstalling it. But it doesn't work with the same error message. 
What can I do? The error message is as follows. Thanks.

[Version]
- Home Assistant: 2023.9.1
- Supervisor: 2023.08.3
- Python: 3.11.5
- aioblescan: 0.2.14
- ble-monitor: 11.8.0 & 12.4.0 

![error](https://github.com/custom-components/ble_monitor/assets/35132274/03d48977-f470-4dce-9765-2650424ffcee)

### Sensor type

ble

### Relevant log output

```shell
Logger: root
Source: custom_components/ble_monitor/__init__.py:720
Integration: Passive BLE monitor (documentation, issues)
First occurred: 9:08:53 (28 occurrences)
Last logged: 9:35:39

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/config/custom_components/ble_monitor/__init__.py", line 720, in run
    initialized_evt[hci] = getattr(btctrl[hci], "_initialized")
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BLEScanRequester' object has no attribute '_initialized'
```

**Comment by Ernst79** [comment]
To be honest, I don't know what is wrong. Its the first time I see this error.
