### ISSUE TITLE
[New Sensor]: Lockin Smart Lock SV40

### ISSUE THREAD

**Issue by zer0factor** [custom-components/ble_monitor#1267]
### Sensor Description

Lockin Smart Lock SV40

### Additional information

MODEL:
loock.lock.v16
https://www.lockin.com.sg/product-page/lockin-push-pull-smart-lock-sv40
This lock can be added in MiHome app. Will grab more adv if insufficient.

### BLE advertisements

```shell
2023-12-06 16:36:54.195 INFO (MainThread) [custom_components.ble_monitor] Attention! Option report_unknown is enabled for sensor with id(s): ['************']
2023-12-06 16:37:05.086 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x0e\x16\x95\xfe\x10U\xc2\x11\xd2=\x04\xa33\x0c\x98']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:37:05.410 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x0e\x16\x95\xfe\x10U\xc2\x11\xd2=\x04\xa33\x0c\x98']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:37:05.736 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x0e\x16\x95\xfe\x10U\xc2\x11\xd2=\x04\xa33\x0c\x98']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:37:38.536 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x17\x16\x95\xfeHU\xc2\x11\xd5%\x04\xb4F\xd5\xa4Z.\xe8\x01\x00\xf7>\xa2\xe9']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:37:40.736 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x17\x16\x95\xfeHU\xc2\x11\xd5%\x04\xb4F\xd5\xa4Z.\xe8\x01\x00\xf7>\xa2\xe9']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:37:40.836 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x17\x16\x95\xfeHU\xc2\x11\xd5%\x04\xb4F\xd5\xa4Z.\xe8\x01\x00\xf7>\xa2\xe9']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:38:11.963 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x1b\x16\x95\xfeHU\xc2\x11\xd9TD\xc3\xd52\x95\xf6\xdc"/\xfa:\xe8\x01\x00\x87\\\xbe\xe0']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:38:12.488 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x1b\x16\x95\xfeHU\xc2\x11\xd9TD\xc3\xd52\x95\xf6\xdc"/\xfa:\xe8\x01\x00\x87\\\xbe\xe0']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:38:13.113 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x1b\x16\x95\xfeHU\xc2\x11\xd9TD\xc3\xd52\x95\xf6\xdc"/\xfa:\xe8\x01\x00\x87\\\xbe\xe0']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:38:13.538 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x1b\x16\x95\xfeHU\xc2\x11\xd9TD\xc3\xd52\x95\xf6\xdc"/\xfa:\xe8\x01\x00\x87\\\xbe\xe0']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:38:13.963 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x1b\x16\x95\xfeHU\xc2\x11\xd9TD\xc3\xd52\x95\xf6\xdc"/\xfa:\xe8\x01\x00\x87\\\xbe\xe0']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:38:14.063 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x1b\x16\x95\xfeHU\xc2\x11\xd9TD\xc3\xd52\x95\xf6\xdc"/\xfa:\xe8\x01\x00\x87\\\xbe\xe0']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:38:22.987 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x17\x16\x95\xfeHU\xc2\x11\xdb\xbbk\xc5&!~`\xd5\xe8\x01\x00\xf1\x9c\x9c\x86']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:38:23.412 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x17\x16\x95\xfeHU\xc2\x11\xdb\xbbk\xc5&!~`\xd5\xe8\x01\x00\xf1\x9c\x9c\x86']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:38:23.612 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x17\x16\x95\xfeHU\xc2\x11\xdb\xbbk\xc5&!~`\xd5\xe8\x01\x00\xf1\x9c\x9c\x86']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:38:24.162 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x17\x16\x95\xfeHU\xc2\x11\xdb\xbbk\xc5&!~`\xd5\xe8\x01\x00\xf1\x9c\x9c\x86']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:38:24.462 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x17\x16\x95\xfeHU\xc2\x11\xdb\xbbk\xc5&!~`\xd5\xe8\x01\x00\xf1\x9c\x9c\x86']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:38:24.987 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x17\x16\x95\xfeHU\xc2\x11\xdb\xbbk\xc5&!~`\xd5\xe8\x01\x00\xf1\x9c\x9c\x86']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:38:27.314 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x1b\x16\x95\xfeHU\xc2\x11\xdd\xb4\xab9Z\x11\xd5\xb8\xa5$4\xbb\x16\xe8\x01\x00\x99\x82tx']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:38:27.413 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x1b\x16\x95\xfeHU\xc2\x11\xdd\xb4\xab9Z\x11\xd5\xb8\xa5$4\xbb\x16\xe8\x01\x00\x99\x82tx']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:38:27.838 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x1b\x16\x95\xfeHU\xc2\x11\xdd\xb4\xab9Z\x11\xd5\xb8\xa5$4\xbb\x16\xe8\x01\x00\x99\x82tx']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:38:28.463 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x1b\x16\x95\xfeHU\xc2\x11\xdd\xb4\xab9Z\x11\xd5\xb8\xa5$4\xbb\x16\xe8\x01\x00\x99\x82tx']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:38:28.788 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x1b\x16\x95\xfeHU\xc2\x11\xdd\xb4\xab9Z\x11\xd5\xb8\xa5$4\xbb\x16\xe8\x01\x00\x99\x82tx']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:38:29.013 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x1b\x16\x95\xfeHU\xc2\x11\xdd\xb4\xab9Z\x11\xd5\xb8\xa5$4\xbb\x16\xe8\x01\x00\x99\x82tx']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:38:29.313 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x1b\x16\x95\xfeHU\xc2\x11\xdd\xb4\xab9Z\x11\xd5\xb8\xa5$4\xbb\x16\xe8\x01\x00\x99\x82tx']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:38:29.413 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x1b\x16\x95\xfeHU\xc2\x11\xdd\xb4\xab9Z\x11\xd5\xb8\xa5$4\xbb\x16\xe8\x01\x00\x99\x82tx']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:38:29.863 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x1b\x16\x95\xfeHU\xc2\x11\xdd\xb4\xab9Z\x11\xd5\xb8\xa5$4\xbb\x16\xe8\x01\x00\x99\x82tx']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:38:29.938 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x1b\x16\x95\xfeHU\xc2\x11\xdd\xb4\xab9Z\x11\xd5\xb8\xa5$4\xbb\x16\xe8\x01\x00\x99\x82tx']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:38:30.464 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x17\x16\x95\xfeHU\xc2\x11\xde\xc5~\x1c\xa1NV\xfa\x13\xe8\x01\x00\x8f\xf6\xfc\x1a']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:38:31.013 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x17\x16\x95\xfeHU\xc2\x11\xde\xc5~\x1c\xa1NV\xfa\x13\xe8\x01\x00\x8f\xf6\xfc\x1a']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:38:31.613 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x17\x16\x95\xfeHU\xc2\x11\xde\xc5~\x1c\xa1NV\xfa\x13\xe8\x01\x00\x8f\xf6\xfc\x1a']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:38:32.163 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x17\x16\x95\xfeHU\xc2\x11\xde\xc5~\x1c\xa1NV\xfa\x13\xe8\x01\x00\x8f\xf6\xfc\x1a']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:38:33.087 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x17\x16\x95\xfeHU\xc2\x11\xde\xc5~\x1c\xa1NV\xfa\x13\xe8\x01\x00\x8f\xf6\xfc\x1a']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:38:33.213 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x17\x16\x95\xfeHU\xc2\x11\xde\xc5~\x1c\xa1NV\xfa\x13\xe8\x01\x00\x8f\xf6\xfc\x1a']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:38:38.760 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x0e\x16\x95\xfe\x10U\xc2\x11\xdf=\x04\xa33\x0c\x98']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:38:39.287 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x17\x16\x95\xfeHU\xc2\x11\xe0\xdd\xcb"[Ae\x8e\x0e\xe8\x01\x00?\xd9\\\xda']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:38:40.012 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x17\x16\x95\xfeHU\xc2\x11\xe0\xdd\xcb"[Ae\x8e\x0e\xe8\x01\x00?\xd9\\\xda']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:38:40.362 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x17\x16\x95\xfeHU\xc2\x11\xe0\xdd\xcb"[Ae\x8e\x0e\xe8\x01\x00?\xd9\\\xda']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:38:40.862 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x17\x16\x95\xfeHU\xc2\x11\xe0\xdd\xcb"[Ae\x8e\x0e\xe8\x01\x00?\xd9\\\xda']manufacturer specific data: []local name: UUID16: None,UUID128: None
2023-12-06 16:38:41.388 INFO (Thread-5) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID ************: service data: [b'\x17\x16\x95\xfeHU\xc2\x11\xe0\xdd\xcb"[Ae\x8e\x0e\xe8\x01\x00?\xd9\\\xda']manufacturer specific data: []local name: UUID16: None,UUID128: None
```

**Comment by Ernst79** [comment]
This lock is a so called MiBeacon Mesh device. It requires a connection to be set up, which isn't possible with BLE monitor (which only monitors passively broadcasting sensors). So, unfortunately, we can't add it to BLE monitor

**Comment by Ernst79** [comment]
Sorry, my mistake, it isn't a mesh device. I'll look further into it

**Comment by zer0factor** [comment]
I've drop you the email.

**Comment by uncle-wong** [comment]
我刚把s30pro加进去，但是童锁，反锁，和撬锁数据不对。

**Comment by zer0factor** [comment]
I've resend the keys.

**Comment by Ernst79** [comment]
Thanks, in MiHome mod (which you used), it is the "beacon_key" that you need. I was able to parse the message, with useful results. I will add the device this weekend most likely. 

{'rssi': -64, 'mac': '980C33A3043D', 'type': 'SV40', 'packet': 20, 'firmware': 'Xiaomi (MiBeacon V5 encrypted)', 'data': True, 'door': 0, 'door action': 'close the door'}

I assume you regenerated the encryption key. If not, please do, because I want to use the data to create tests.

**Comment by Ernst79** [comment]
Do you know your lock is supporting the following features?
- "fingerprint"
- "antilock"
- "childlock"

**Comment by zer0factor** [comment]
Hi Ernst,

Yes I did a repairing for the key.

The lock support fingerprint(finger vein) is the same I suppose.

The lock support child lock and antilock.

Let me know if you need more data.

**Comment by uncle-wong** [comment]
好用了么？我也是这么添加的我的鹿客s30pro，童锁，反锁和撬门状态是未知的。你的哪个数据是怎么搞出来？

**Comment by Ernst79** [comment]
an explanation how to get the data is provided here https://custom-components.github.io/ble_monitor/sensor_request#getting-ble-advertisements-with-the-home-assistant-logger

**Comment by uncle-wong** [comment]
我通过esphome的蓝牙代理获得了这样的数据，10:51:11	[D]	[ble_gateway:063]	
[84:71:27:6E:43:31] Packet 043E1E0201000031436E277184120201060E1695FE1055F70B7C31436E277184BC，也获得了encryption key，我按照Q2写法更改了部分代码，但是现在童锁等不可用，当我尝试打开与关闭童锁时，报错如下：
2023-12-23 10:54:08.200 ERROR (Thread-6) [homeassistant] Error doing job: Fatal error: protocol.data_received() call failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 1003, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.11/site-packages/aioblescan/aioblescan.py", line 1855, in data_received
    self.process(packet)
  File "/config/custom_components/ble_monitor/__init__.py", line 586, in process_hci_events
    sensor_msg, tracker_msg = self.ble_parser.parse_raw_data(data)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ble_monitor/ble_parser/__init__.py", line 164, in parse_raw_data
    sensor_data, tracker_data = self.parse_advertisement(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ble_monitor/ble_parser/__init__.py", line 248, in parse_advertisement
    sensor_data = parse_xiaomi(self, service_data, mac, rssi)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ble_monitor/ble_parser/xiaomi.py", line 1275, in parse_xiaomi
    result.update(resfunc(dobject, device_type))
TypeError: 'NoneType' object is not iterable
请问如何使用/test/test_xiaomi_parser.py?我在ha中运行，提示no ble_monitor.ble_parser module。

如何解决上述问题？请不吝赐教，谢谢
