### ISSUE TITLE
component cannot be started

### ISSUE THREAD

**Issue by fabiogfabio** [custom-components/ble_monitor#1312]
HI
when I install the component I can select the BT hardware and so far everything is fine when I save it gives me these errors:

2024-02-18 02:34:10.645 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 72, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 223, in post
    return await super().post(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 345, in async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 501, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ble_monitor/config_flow.py", line 488, in async_step_init
    for dev in self.config_entry.options.get(CONF_DEVICES):
TypeError: 'NoneType' object is not iterable

Can you help me understand what caused it?

tnx!!!
![3_issue](https://github.com/custom-components/ble_monitor/assets/58087792/4515594c-ede1-46f6-9628-75dc2b11a80c)
![2_issue](https://github.com/custom-components/ble_monitor/assets/58087792/29800926-d6fc-475d-969a-5b01203d30c1)
![1_issue](https://github.com/custom-components/ble_monitor/assets/58087792/a4eccab0-c3f3-4f02-a46d-b801eb859b55)

**Comment by Ernst79** [comment]
Hmmm, strange. Never seen this error before. Can you try to add a (dummy) device (last option in your screenshot). Just ad a device with MAC address 11:22:33:44:55:66 or something like that

**Comment by fabiogfabio** [comment]
> Hmmm, strange. Never seen this error before. Can you try to add a (dummy) device (last option in your screenshot). Just ad a device with MAC address 11:22:33:44:55:66 or something like that

![Screenshot_2024-02-18-09-36-49-16_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/custom-components/ble_monitor/assets/58087792/f7575fcd-7f92-4b52-86b0-1467aae1ef61)
![Screenshot_2024-02-18-09-36-42-69_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/custom-components/ble_monitor/assets/58087792/c0ef5112-2dbc-4e49-8522-d0fa6b3b7c52)

**Comment by CalamityJenn** [comment]
Hi, I'm facing this exact scenario. I cannot use Passive BLE Monitor anymore.
I've got "**_500 Internal Server Error Server got itself in trouble_**" when I try to (re)configure the integration.

It was fully functionnal since 2020 and it suddently got mad right after core_2024.5.5 update I've applied on June, 14th, HA does not get data from none of my dozens ble sensors, whatever I try.
