### ISSUE TITLE
[Bug]: All Xiaomi CGG1 are unavailable after update to HA 2024.6.0

### ISSUE THREAD

**Issue by R1DEN** [custom-components/ble_monitor#1363]
### What happened?

All Xiaomi CGG1 became unavailable after update to HA 2024.6.0

### Sensor type

Xiaomi CGG1

### Relevant log output

```
2024-06-06 08:18:01.959 DEBUG (MainThread) [custom_components.ble_monitor.config_flow] async_step_init user_input: None
2024-06-06 08:18:01.959 DEBUG (MainThread) [custom_components.ble_monitor.config_flow] async_step_init (before): {'bt_interface': ['18:1D:EA:F5:C0:39'], 'bt_auto_restart': True, 'active_scan': False, 'discovery': False, 'period': 10, 'use_median': False, 'log_spikes': False, 'restore_state': False, 'report_unknown': 'Off', 'devices': [{'mac': '5A:58:2D:34:12:60', 'name': 'Bathroom Temperature Humidity'}, {'mac': '5A:58:2D:34:12:5E', 'name': 'Bedroom Temperature Humidity'}, {'mac': '5A:58:2D:34:12:5F', 'name': 'Hallway Temperature Humidity'}, {'mac': '5A:58:2D:34:12:61', 'name': 'Living Temperature Humidity'}], 'is_flow': True, 'hci_interface': [0]}
2024-06-06 08:18:01.959 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 262, in post
    return await super().post(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 70, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 77, in post
    return await self._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 84, in _post_impl
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 343, in async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ble_monitor/config_flow.py", line 490, in async_step_init
    devreg = self.hass.helpers.device_registry.async_get(self.hass)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: async_get() takes 1 positional argument but 2 were given
```

**Comment by R1DEN** [comment]
Reverted back to 2024.5.5 and it works again

**Comment by Ernst79** [comment]
It looks like your ble monitor version is outdated. Which version do you have?. If I look at line 490, it has already changed to

`devreg = device_registry.async_get(self.hass)`

**Comment by R1DEN** [comment]
Yeah, I was 1 or 2 minor versions behind, I'll update it and report back

**Comment by R1DEN** [comment]
Yup, everything works. Thank you!
