### ISSUE TITLE
[Bug]: Relsib device fails with KeyError: 'EClerk Eco'

### ISSUE THREAD

**Issue by nickolay** [custom-components/ble_monitor#1394]
### What happened?

This device https://custom-components.github.io/ble_monitor/by_brand#relsib used to work before, but with 12.15 I'm getting an error in the logs whenever the device is turned on.

This commit added support https://github.com/custom-components/ble_monitor/commit/17bef09adbb9a242922752c97b46751e293e86d4#diff-0494dc94aec31d1305bb882f071fbe41b1aa71748d40038ed771b8460a248c96L116
I guess, this commit broke it: https://github.com/custom-components/ble_monitor/commit/afe338d2599590d3f84857dedc143b3cfa6077dd#diff-fd1a5033fe5addac5ed88ecfb49ddd343180deecdd1597913489b5f9a4f7a2e2L17

Adding back the removed line to `custom_components/ble_monitor/const.py` makes the device work as before:
```
MEASUREMENT_DICT = {
...
   'EClerk Eco'              : [["temperature", "humidity", "co2", "battery", "rssi"], [], []],
```

### Relevant log output

```shell
2024-10-21 23:56:29.678 ERROR (Thread-2) [homeassistant] Error doing job: Fatal error: protocol.data_received() call failed. (None)
Traceback (most recent call last):
File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1017, in _read_ready__data_received
self._protocol.data_received(data)
File "/usr/local/lib/python3.12/site-packages/aioblescan/aioblescan.py", line 1855, in data_received
self.process(packet)
File "/config/custom_components/ble_monitor/__init__.py", line 589, in process_hci_events
MEASUREMENT_DICT[device_type][0] + MEASUREMENT_DICT[device_type][1]
~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'EClerk Eco'
```

**Comment by nickolay** [comment]
Thanks, with 12.17 everything works again: the error is gone, the co2, humidity and temp values are reported correctly, among others.
