### ISSUE TITLE
[Bug]:After HASS core update 2024.12.3 integration does not work for me  

### ISSUE THREAD

**Issue by IvanGerr** [custom-components/ble_monitor#1416]
### What happened?

HASS core v. 2024.12.1 works fine. I skipped v. 2024.12.2 so not sure about it. 
I use BLE for Xiaomi temp/humidity  sensors modified to ATC firmware which is not currenty transfered from ble monitor to HASS native support, so guess I'm staying at 2024.12.1 till that.

**Comment by Ernst79** [comment]
Can't help you, without any errors. It is working fine on my end. Try a full system restart (not only a HA restart, but power off, power on), possibly an OS update messed things up.

**Comment by IvanGerr** [comment]
Tried full restart. Doesn't help. I could gather required info if you can give a hint where to look at. All I see is just red exclamation mark on integration saying "Check journals" (its translation, not exact as in En version) and all sensors tell something like "data is not provided by integration anymore".

**Comment by Ernst79** [comment]
Have a look into the logs of home assistant, if there are any errors in your home assistant logbook.

**Comment by agilob** [comment]
I'm getting this. I've tried reinstalling ble multiple times, downgrading, upgrading. Happens on 12.19.0, 12.20.0 and 13.0.0-beta
```
Stack (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 708, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 679, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2027, in _run_once
    handle._run()
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2353, in async_forward_entry_setup
    _report_non_awaited_platform_forwards(entry, "async_forward_entry_setup")
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1199, in _report_non_awaited_platform_forwards
    report_usage(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 234, in report_usage
    _LOGGER.warning(msg, stack_info=True)
2024-12-16 08:40:02.033 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'ble_monitor': Unable to import component: No module named 'aioblescan'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1014, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/ble_monitor/__init__.py", line 8, in <module>
    import aioblescan as aiobs
```

**Comment by Ernst79** [comment]
The problem is this line

`Setup failed for custom integration 'ble_monitor': Unable to import component: No module named 'aioblescan'`

Somehow, aioblescan is not installed or not installed properly. This should be done automatically when you install BLE monitor. 

What you can try is to remove BLE monitor all together, restart HA, and re-add it again.

**Comment by agilob** [comment]
>What you can try is to remove BLE monitor all together, restart HA, and re-add it again.

Tried it twice and it didn't help.

**Comment by Ernst79** [comment]
What kind of operating system do you use, Home Assistant OS? or a differen OS. can you check if aioblescan is installed or install it manually?

**Comment by agilob** [comment]
i run hass in a container. I run pip install:
```
❯ k exec hass-home-assistant-0 -it -- bash
Defaulted container "hass-home-assistant" out of: hass-home-assistant, eufywsaddon
hass:/config# pip install aioblescan
Looking in indexes: https://pypi.org/simple, https://wheels.home-assistant.io/musllinux-index/
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f9f49a9f0>: Failed to establish a new connection: [Errno -3] Try again')': /simple/aioblescan/
Collecting aioblescan
  Downloading aioblescan-0.2.14-py3-none-any.whl.metadata (8.1 kB)
Downloading aioblescan-0.2.14-py3-none-any.whl (27 kB)
Installing collected packages: aioblescan
Successfully installed aioblescan-0.2.14
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
```

restarted hass container and it worked :eyes:

**Comment by Ernst79** [comment]
Great. strange that it didn't install automagically, but at least it is working again.

**Comment by IvanGerr** [comment]
I updated hass core once again to 2024.12.3. Ble monitor does not report any errors. ¯\_(ツ)_/¯
Issue may be closed I guess.

**Comment by Ernst79** [comment]
great. Not sure why these things happen and why they solve themself. Lets hope it was just bad luck :-) Thanks for reporting back.
