### ISSUE TITLE
Stopped working after reboot HA

### ISSUE THREAD

**Issue by feroxes** [custom-components/ble_monitor#164]
It worked fine, when first time I installed it, but after rebooting of home assistant, data is unavailable.

     platform: ble_monitor
     rounding: True
     decimals: 2
     period: 60
     log_spikes: False
     use_median: False
     active_scan: False
     hci_interface: 0

<img src="https://a.radikal.ru/a32/2011/c6/41fd2d2762f8.png" />

log

> 2020-11-21 12:15:21 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-11-21 12:15:24 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for ble_monitor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-11-21 12:15:25 ERROR (MainThread) [homeassistant.setup] Error during setup of component ble_monitor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
result = await task
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/ble_monitor/__init__.py", line 87, in setup
hass.data[DOMAIN] = config[DOMAIN]
KeyError: 'ble_monitor'
2020-11-21 12:15:25 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform ble_monitor.sensor: Unable to set up component.
2020-11-21 12:15:36 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up upnp platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
await asyncio.shield(task)
File "/usr/src/homeassistant/homeassistant/components/upnp/sensor.py", line 93, in async_setup_entry
device: Device = hass.data[DOMAIN][DOMAIN_DEVICES][udn]
KeyError: 'uuid:eba8b314-4cd4-4d3f-b108-eb00e36bcb16'
2020-11-21 12:15:38 ERROR (MainThread) [custom_components.hacs.factory] fineemb/lynk-co - GitHub returned 404 for https://api.github.com/repos/fineemb/lynk-co

**Comment by Magalex2x14** [comment]
Hello!
Seems like the problem is not with the component, it is system-wide, judging by the log. First, check your configuration.yaml file.

**Comment by feroxes** [comment]
Hi)
What exactly should I check? I didn't touch it. 
I include sensors
sensor: !include_dir_merge_list includes/sensor

in includes/sensor/ble_monitor.yaml I have this config
```py
 -  platform: ble_monitor
    rounding: True
    decimals: 2
    period: 60
    log_spikes: False
    use_median: False
    active_scan: False
    hci_interface: 0
```

**Comment by feroxes** [comment]
Data in dev tools unavailable( 

<img src="https://d.radikal.ru/d14/2011/11/8e6ede72735a.png" />

**Comment by Ernst79** [comment]
It isn't an sensor platform anymore. It is an integration on its own. 

In configuration.yaml, it looks like this.

```
ble_monitor
    rounding: True
    decimals: 2
    period: 60
    log_spikes: False
    use_median: False
    active_scan: False
    hci_interface: 0
```

So do not use `sensor: !include_dir_merge_list includes/sensor`, but something like `ble_monitor: !include_dir_merge_list includes/ble_monitor`

**Comment by feroxes** [comment]
It helps:)) thank you very match! 
Have a nice day🤟
