### ISSUE TITLE
Losing Wifi Connection when enabling ble_monitor

### ISSUE THREAD

**Issue by buettnc** [custom-components/ble_monitor#169]
I have installed ble_monitor 0.8.3 using HACS (1.6.2) with docker home assistant 0.117.0 running on RPi4b  4.0 Gb w/ python 3.8.6.  
When I add the ble_monitor: line the configuration.yaml file the home_assistant.log reports that it is unable to connect to device(s) 192.168.1.* .  
-------------------------------------------------------------------------------------
2020-11-22 15:30:26 ERROR (SyncWorker_3) [homeassistant.components.tplink.common] Unable to connect to device 192.168.1.10: Communication error
2020-11-22 15:30:31 ERROR (SyncWorker_3) [homeassistant.components.tplink.common] Unable to connect to device 192.168.1.7: Communication error

Also cannot connect with UPnP devices
-----------------------------------------------------
2020-11-22 15:30:39 INFO (MainThread) [homeassistant.components.upnp] No UPnP/IGD devices discovered
2020-11-22 15:30:39 INFO (MainThread) [homeassistant.components.upnp] Unable to create UPnP/IGD, aborting

It is however successful finding BLE devices and adding them.
2020-11-22 15:30:21 DEBUG (MainThread) [custom_components.ble_monitor.sensor] async_added_to_hass called for ble temperature A4C1389861F6
2020-11-22 15:30:21 DEBUG (MainThread) [custom_components.ble_monitor.sensor] async_added_to_hass called for ble humidity A4C1389861F6

After the "HACS (Home Assistant Community Store)" banner I get the following error
----------------------------------------------------------------------------------------------------------------
2020-11-22 15:30:50 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 234, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/hacs/__init__.py", line 30, in async_setup_entry
    return await hacs_ui_setup(hass, config_entry)
  File "/config/custom_components/hacs/operational/setup.py", line 66, in async_setup_entry
    return await async_startup_wrapper_for_config_entry()
  File "/config/custom_components/hacs/operational/setup.py", line 91, in async_startup_wrapper_for_config_entry
    startup_result = await async_hacs_startup()
  File "/config/custom_components/hacs/operational/setup.py", line 139, in async_hacs_startup
    await async_setup_frontend()
  File "/config/custom_components/hacs/operational/setup_actions/frontend.py", line 38, in async_setup_frontend
    hacs.hass.components.frontend.async_register_built_in_panel(
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 196, in async_register_built_in_panel
    raise ValueError(f"Overwriting panel {panel.frontend_url_path}")
ValueError: Overwriting panel hacs
2020-11-22 15:30:51 ERROR (SyncWorker_3) [homeassistant.components.tplink.common] Unable to connect to device 192.168.1.12: Communication error
2020-11-22 15:30:56 ERROR (SyncWorker_3) [homeassistant.components.tplink.common] Unable to connect to device 192.168.1.6: Communication error

When I start a shell in the home assistant docker container and try to ping a known device (192.168.1.2) I get no response.  

Any idea as to why my wlan0 connection is shutdown when I enable this integration?

**Comment by Magalex2x14** [comment]
Hey. Someone already had something like this (discussed on the forum, he had a Surface pro tablet with a linux build I haven't heard of before). Earlier I read about problems with bluetooth with active wifi traffic. We did not find a solution then, and it all ended with the fact that he would try an external bt-dongle.

The root of the problem, perhaps, lies in the fact that the raspberry uses one chip for both types of communication, and it is quite possible that you have encountered some kind of problem in implementing its support in Linux.

Tell me, what version of HassOS do you have now? Version 4.14 or 4.13 had serious problems with this.

**Comment by nimnes** [comment]
I had same issue on RPi4b and for me it was solved by switching Wifi from 2.4Ghz to 5Ghz. There is a [thread](https://indilib.org/forum/general/6576-pi4-usb3-and-wireless-2-4ghz-interference.html) about Pi4, USB3 and Wifi 2.4GHz interference, which can be related to Bluetooth problem as well.

**Comment by Ernst79** [comment]
Closing this issue. Feel free to reopen if you still have the issue.

**Comment by Taylor-Carnell** [comment]
> I had same issue on RPi4b and for me it was solved by switching Wifi from 2.4Ghz to 5Ghz. There is a [thread](https://indilib.org/forum/general/6576-pi4-usb3-and-wireless-2-4ghz-interference.html) about Pi4, USB3 and Wifi 2.4GHz interference, which can be related to Bluetooth problem as well.

Had the same issue with my Rpi4 nearly grinding to a halt with this integration. 5ghz fixed the problem. Cheers
