### ISSUE TITLE
Config flow issues

### ISSUE THREAD

**Issue by Ernst79** [custom-components/ble_monitor#197]
Config flow is giving the following error after adding a non-existing MAC

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 210, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 69, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 130, in async_init
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 213, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/ble_monitor/config_flow.py", line 331, in async_step_init
    sorteddev_tuples = sorted(self._devices.items(), key=lambda item: item[1]["name"])
  File "/config/custom_components/ble_monitor/config_flow.py", line 331, in <lambda>
    sorteddev_tuples = sorted(self._devices.items(), key=lambda item: item[1]["name"])
KeyError: 'name'
```

**Comment by Magalex2x14** [comment]
I cannot reproduce this error

**Comment by Magalex2x14** [comment]
Happened. After adding a new mac address, an error occurs when trying to enter the integration settings

**Comment by Ernst79** [comment]
yes, correct. Happens for me as well, it's the same error as you had in #75. The device isn't added in my case, as it is an non-existing device.

**Comment by Ernst79** [comment]
Confirm it is fixed
