### ISSUE TITLE
crashed when looking for devices

### ISSUE THREAD

**Issue by henrykey** [custom-components/ble_monitor#203]
installation is ok. I get it from HACS and install the integration successfully. but get error messags as following repeatly:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/config/custom_components/ble_monitor/__init__.py", line 528, in run
    self._event_loop.run_until_complete(btctrl[hci].stop_scan_request())
KeyError: 0

Is I missing somthing? or something wrong?

thanks!
Henry

**Comment by Ernst79** [comment]
Did you configure the integration in YAML or in the User Interface? And can you explain what you mean with “when looking for devices”

**Comment by henrykey** [comment]
I was just following your instruction to install it from HACS. Then, choose the method of 4a for adding devices. nothing found and I checked the system log found a bunch of the same errors that posted. 
what I said 'when looking for devices' means when the integration was running to scan blue tooth devices. 
when I restart hass, just get a warning:
2020-12-19 21:45:08 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for ble_monitor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
if I reload your integration by click menu item of reload in it, the error display in system log again.
2020-12-19 21:46:09 ERROR (Thread-4) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/config/custom_components/ble_monitor/__init__.py", line 528, in run
    self._event_loop.run_until_complete(btctrl[hci].stop_scan_request())
KeyError: 0
2020-12-19 21:47:10 ERROR (Thread-11) [custom_components.ble_monitor] HCIdump thread: OS error (hci0): [Errno 19] error while attempting to bind on interface 0: No such device
2020-12-19 21:47:28 ERROR (Thread-11) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/config/custom_components/ble_monitor/__init__.py", line 528, in run
    self._event_loop.run_until_complete(btctrl[hci].stop_scan_request())
KeyError: 0
2020-12-19 21:47:28 ERROR (Thread-12) [custom_components.ble_monitor] HCIdump thread: OS error (hci0): [Errno 19] error while attempting to bind on interface 0: No such device

**Comment by Ernst79** [comment]
The last error explains the problem, it can't find a device (bluetooth dongle or internal bluetooth radio) on hci0. You need to find the correct number. To find the correct number, run the following command:

`hcitool dev`

The command will return the HCI interface number and mac address.

```
Devices:
        hci0    B8:27:EB:77:75:50
```

You can also just try hci1 instead of hci0.

**Comment by Ernst79** [comment]
Fix is submitted for better Error Handling.

**Comment by henrykey** [comment]
let me try it again

**Comment by henrykey** [comment]
my hass.io is installed in a virtualbox and no Bluetooth device available. is this the problem?

**Comment by Ernst79** [comment]
Your Bluetooth device should be accessible for your home assistant, otherwise it won’t work. I think you will have to give the virtualbox access to your Bluetooth device, but I haven’t used a virtualbox myself. 

https://scribles.net/enabling-bluetooth-in-virtualbox/

are you running virtualbox on Linux or Windows?

**Comment by henrykey** [comment]
im running virtualbox on linux, ubuntu 20.04

**Comment by Ernst79** [comment]
Ok, let us know if it works after enabling access to bluetooth.

**Comment by henrykey** [comment]
got another issue that your integration can't be found from the menu item of adding integrations. I installed a supervised hassio on my ubtuntu 20.04 and installed the component from hacs. the difference from installing in VM is two more commands being executed.
sudo setcap 'cap_net_raw,cap_net_admin+eip' `readlink -f \`which python3\``
and getcap return /home/henry/.pyenv/shims/python3 = cap_net_admin,cap_net_raw+eip
im not sure is this a problem cuz there several versions of python in my system and this one is not the same one hass used. it's python 3.8.4. I tried reinstalling the passion integration and still have the same problem.
what should i going to try?

**Comment by Ernst79** [comment]
The commands or python version should not make a difference for the integration being available in the menu. Couple of first thing to check

- did you restart HA after the installation?
- Is there a folder config/custom_components/ble_monitor with content on your system. 
- check the read right of this folder, is is accessible for the HA user
- Try reinstalling it with hacs

**Comment by henrykey** [comment]
yes, I did. it shows up after reboot my computer. and have a notification that has new beta version available. installation is ok now and errors are different now:
2020-12-21 16:01:46 ERROR (Thread-13) [custom_components.ble_monitor] HCIdump thread: Runtime error while sending scan request on hci0: Event loop stopped before Future completed.
2020-12-21 16:02:53 ERROR (MainThread) [custom_components.ble_monitor] Waiting for the HCIdump thread to finish took too long! (>10s)
2020-12-21 16:02:53 ERROR (Thread-13) [custom_components.ble_monitor] HCIdump thread: Runtime error while stop scan request on hci0: Event loop stopped before Future completed.
2020-12-21 16:03:53 ERROR (Thread-14) [custom_components.ble_monitor] HCIdump thread: Runtime error while sending scan request on hci0: Event loop stopped before Future completed.
2020-12-21 16:05:54 ERROR (Thread-14) [custom_components.ble_monitor] HCIdump thread: Runtime error while stop scan request on hci0: Event loop stopped before Future completed.

**Comment by henrykey** [comment]
PS. I have reinstalled it already.

**Comment by henrykey** [comment]
Hi, it works now. The problem is I forgot that I turn off the Bluetooth for VM setup. after turn on. all my Bluetooth devices are coming up.
Thanks
