### ISSUE TITLE
Error while attempting to bind on interface.

### ISSUE THREAD

**Issue by Ssereno** [custom-components/ble_monitor#216]
I have update my ble_monitor and now i get this erro:

2020-12-24 12:47:03 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for ble_monitor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-12-24 12:47:05 ERROR (Thread-3) [custom_components.ble_monitor] HCIdump thread: OS error (hci0): [Errno 19] error while attempting to bind on interface 0: No such device
2020-12-24 12:48:06 ERROR (Thread-3) [root] Uncaught thread exception
Traceback (most recent call last):
File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
File "/config/custom_components/ble_monitor/__init__.py", line 528, in run
self._event_loop.run_until_complete(btctrl[hci].stop_scan_request())
KeyError: 0

My config.
# Sensores Temperatura
ble_monitor:
    rounding: False
    decimals: 1
    period: 60
    log_spikes: True
    use_median: False
    active_scan: False
    hci_interface: 0
    discovery: True
    restore_state: True
    devices:
    - mac: 'A4:C2:38:A4:7D:5E'
      name: 'Sala Estar'
      encryption_key: 'bcdd8dda5e19039f526cdb1d62425934'
      temperature_unit: C
    - mac: '58:2D:34:38:99:GH'
      name: 'Piso 1'
      temperature_unit: C

and running Home Assistant 0.118.5.

Any ideia?

**Comment by Ssereno** [comment]
Problem solved. I just update my bluetooth driver and restart the server and now is running fine
