### ISSUE TITLE
Error: Address family not supported by protocol

### ISSUE THREAD

**Issue by takthetank** [custom-components/ble_monitor#243]
Hello, I'm currently receiveing the following error in logs:

```
OSError: [Errno 97] Address family not supported by protocol

2021-01-23 15:07:41 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved

Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/components/bluetooth_tracker/device_tracker.py", line 177, in update_bluetooth

    await perform_bluetooth_update()

  File "/usr/src/homeassistant/homeassistant/components/bluetooth_tracker/device_tracker.py", line 140, in perform_bluetooth_update

    devices = await hass.async_add_executor_job(discover_devices, device_id)

  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run

    result = self.fn(*self.args, **self.kwargs)

  File "/usr/src/homeassistant/homeassistant/components/bluetooth_tracker/device_tracker.py", line 57, in discover_devices

    result = bluetooth.discover_devices(

  File "/usr/local/lib/python3.8/site-packages/bluetooth/bluez.py", line 26, in discover_devices

    device_id = _bt.hci_get_route()

OSError: [Errno 97] Address family not supported by protocol
```

YAML config is as follows
```yaml
ble_monitor:
  hci_interface: 
    - 0
    - 1
  discovery: True
  active_scan: False
  report_unknown: False
  batt_entities: False
  rounding: True
  decimals: 1
  period: 60
  log_spikes: False
  use_median: False
  restore_state: False
  devices:
    - mac: 'the MAC'
      name: 'vtak-alarm'
      encryption_key: 'the KEY'
      temperature_unit: C
```

Homeassistant running on Docker, on a Synology DS720+ with bluetooth usb donlge.
I'm trying to connect to a CGD1 (qingping alarm clock).

**Comment by Ernst79** [comment]
These errors are related to the bluetooth_tracker component, not from ble_monitor. 

I think you should report your issue at the developers of the bluetooth_tracker component

**Comment by Ernst79** [comment]
Note that two Bluetooth component can interfere with eachother. The FAQ gives some explanation and solutions (e.g an extra Bluetooth dongle).

**Comment by takthetank** [comment]
Sorry I post the wrong log, I'm getting the same for BLE as well.

Ok I'll check to see if they interfere.

```
Logger: custom_components.ble_monitor
Source: custom_components/ble_monitor/__init__.py:513
Integration: Passive BLE monitor (documentation)
First occurred: 5:16:35 PM (230 occurrences)
Last logged: 7:10:47 PM

HCIdump thread: OS error (hci0): [Errno 97] Address family not supported by protocol
HCIdump thread: OS error (hci1): [Errno 97] Address family not supported by protocol
```

**Comment by Ernst79** [comment]
Seems to be similar as reported here

https://community.home-assistant.io/t/bluetooth-issue-please-help/101503/2

**Comment by Ernst79** [comment]
Closing this issue. Feel free to reopen.

**Comment by takthetank** [comment]
I used a new bluetooth dongle and everything is working fine now, so maybe there was an issue with the first one or the bluetooth version (v. 3) isn't supported.
