### ISSUE TITLE
parser error??

### ISSUE THREAD

**Issue by jaxc0402** [custom-components/ble_monitor#373]
With the latest update I get : 

Logger: homeassistant
Source: custom_components/ble_monitor/ble_parser/__init__.py:21 
Integration: Passive BLE monitor (documentation, issues) 
First occurred: 8:59:49 (1 occurrences) 
Last logged: 8:59:49

Error doing job: Fatal error: protocol.data_received() call failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 862, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.8/site-packages/aioblescan/aioblescan.py", line 1852, in data_received
    self.process(packet)
  File "/config/custom_components/ble_monitor/__init__.py", line 484, in process_hci_events
    msg = ble_parser(self, data)
  File "/config/custom_components/ble_monitor/ble_parser/__init__.py", line 21, in ble_parser
    adpayload_size = data[adpayload_start - 1]
IndexError: index out of range

**Comment by Ernst79** [comment]
Thanks for reporting. Should be fixed in 2.6.1, which is just released.
