### ISSUE TITLE
Mosquito Repellent - sensor unavailable

### ISSUE THREAD

**Issue by andrewjswan** [custom-components/ble_monitor#396]
After upgrade to 3.0.0
battery and consumable sensors for mosquito repellent - unavailable, 

![image](https://user-images.githubusercontent.com/3609660/121004110-f25af080-c796-11eb-9324-e62d6fe2deb7.png)

In log only:
```
2021-06-07 12:04:52 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/ble_monitor/sensor.py", line 131, in async_run
sensors = await async_add_sensor(mac, sensortype, firmware)
File "/config/custom_components/ble_monitor/sensor.py", line 98, in async_add_sensor
sensors.insert(device_sensors.index(sensor), globals()[SENSOR_DICT[sensor]](
KeyError: 'non-stabilized weight'
```

**Comment by Ernst79** [comment]
Fixed in 3.0.1, which has been released a minute ago.
