### ISSUE TITLE
Xiaomi Kettle error

### ISSUE THREAD

**Issue by perseus177** [custom-components/ble_monitor#404]
HA version - 2021.5.5
BLE version - 3.0.1
Problematic device - YM-K1501

This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/ble_monitor/sensor.py:402
Integration: Passive BLE monitor (documentation, issues)
First occurred: 9:33:32 (140 occurrences)
Last logged: 11:12:36

```
Update for sensor.ble_temperature_ac9a22f296d0 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 316, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 524, in async_device_update
    raise exc
  File "/config/custom_components/ble_monitor/sensor.py", line 402, in async_update
    state_median = round(sts.median(measurements), rdecimals)
  File "/usr/local/lib/python3.8/statistics.py", line 430, in median
    raise StatisticsError("no median for empty data")
statistics.StatisticsError: no median for empty data
```

**Comment by Ernst79** [comment]
Is already fixed in 3.2.1
