### ISSUE TITLE
Mi Scale V2 sensor error

### ISSUE THREAD

**Issue by tolkonepiu** [custom-components/ble_monitor#413]
Mi Scale sensors doesn't work after upgrade to 3.3.4 version. I receive the following error message:
```
Error doing job: 
Task exception was never retrievedTraceback (most recent call last):
File "/config/custom_components/ble_monitor/binary_sensor.py", line 119, in async_run 
sensors = await async_add_binary_sensor(mac, sensortype, firmware) 
File "/config/custom_components/ble_monitor/binary_sensor.py", line 86, in async_add_binary_sensor sensors.insert(device_sensors.index(sensor), globals()[BINARY_SENSOR_DICT[sensor]]( 
KeyError: 'weight'
```

**Comment by Ernst79** [comment]
Fixed in 3.3.5
