### ISSUE TITLE
No such file or directory: 'hciconfig' - on Pi4 (Ubuntu 20.04) Installed HA with Snap

### ISSUE THREAD

**Issue by Skyridr** [custom-components/ble_monitor#420]
So I'm trying to install BLE monitor on Home Assistant (using Ubuntu 20.04, snap version) but everything I attempt to do so, I keep getting the error [Errno 2] No such file or directory: 'hciconfig' with this in the logs:

```py
Traceback (most recent call last):
  File "/snap/home-assistant-snap/285/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/snap/home-assistant-snap/285/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/snap/home-assistant-snap/285/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/snap/home-assistant-snap/285/lib/python3.8/site-packages/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/snap/home-assistant-snap/285/lib/python3.8/site-packages/homeassistant/components/http/forwarded.py", line 76, in forwarded_middleware
    return await handler(request)
  File "/snap/home-assistant-snap/285/lib/python3.8/site-packages/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/snap/home-assistant-snap/285/lib/python3.8/site-packages/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/snap/home-assistant-snap/285/lib/python3.8/site-packages/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/snap/home-assistant-snap/285/lib/python3.8/site-packages/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/snap/home-assistant-snap/285/lib/python3.8/site-packages/homeassistant/components/config/config_entries.py", line 128, in post
    return await super().post(request)
  File "/snap/home-assistant-snap/285/lib/python3.8/site-packages/homeassistant/components/http/data_validator.py", line 63, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/snap/home-assistant-snap/285/lib/python3.8/site-packages/homeassistant/helpers/data_entry_flow.py", line 72, in post
    result = await self._flow_mgr.async_init(
  File "/snap/home-assistant-snap/285/lib/python3.8/site-packages/homeassistant/data_entry_flow.py", line 153, in async_init
    flow, result = await task
  File "/snap/home-assistant-snap/285/lib/python3.8/site-packages/homeassistant/data_entry_flow.py", line 171, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/snap/home-assistant-snap/285/lib/python3.8/site-packages/homeassistant/config_entries.py", line 696, in async_create_flow
    integration.get_platform("config_flow")
  File "/snap/home-assistant-snap/285/lib/python3.8/site-packages/homeassistant/loader.py", line 498, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/snap/home-assistant-snap/285/lib/python3.8/site-packages/homeassistant/loader.py", line 503, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/snap/home-assistant-snap/285/custom_components/ble_monitor/__init__.py", line 75, in <module>
    BT_INTERFACES = hci_get_mac([0, 1, 2, 3])
  File "/var/snap/home-assistant-snap/285/custom_components/ble_monitor/ble_parser/__init__.py", line 91, in hci_get_mac
    output = subprocess.run(["hciconfig"], stdout=subprocess.PIPE).stdout.decode("utf-8")
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'hciconfig'
```

Any idea why? The error output isn't that detailed. Says no such file/directory, but isn't very specific about it.

```
root@Pi4:/var/snap/home-assistant-snap/current# whereis hciconfig
hciconfig: /usr/bin/hciconfig /usr/share/man/man1/hciconfig.1.gz
root@Pi4:/var/snap/home-assistant-snap/current#
```

Seems to exist just fine on the OS.

**Comment by Ernst79** [comment]
The error is saying that it can't find hciconfig

`FileNotFoundError: [Errno 2] No such file or directory: 'hciconfig'`

hciconfig is part of the `bluez` package, so try

`apt-get install bluez` or `sudo apt-get install bluez`

On most systems, this is installed by default, but apparently not on your Ubuntu snap edition.

**Comment by Skyridr** [comment]
Thanks for your reply! But it appears I already have bluez installed:

```
bluez is already the newest version (5.53-0ubuntu3.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by Ernst79** [comment]
I'm not familiar with snap. But can you run `hciconfig` commands like `hcitool lescan` yourself? Make sure you are in the same environment that HA is using.

**Comment by Skyridr** [comment]
Ya, I can run `hcitool lescan` which shows tons of bluetooth devices. 

As for snap:
```
Snap is a software packaging and deployment system developed by Canonical for operating systems that use the Linux kernel. The packages, called snaps, and the tool for using them, snapd, work across a range of Linux distributions and allow upstream software developers to distribute their applications directly to users
```
It's similar to apt install. HA isn't running in any py env though.

**Comment by Ernst79** [comment]
Did you follow the first step of the instructions? Running this command?

`sudo setcap 'cap_net_raw,cap_net_admin+eip' `readlink -f \`which python3\`` `

**Comment by Skyridr** [comment]
That's the first thing I did yesterday:

`/usr/bin/python3.8 = cap_net_admin,cap_net_raw+eip`

**Comment by Ernst79** [comment]
perhaps an issue with the rights of running hciconfig

can you check the rights of `/usr/bin/hciconfig`. Is the HA user allowed to run hciconfig? `sudo chmod +x /usr/bin/hciconfig` (or without sudo)

**Comment by Skyridr** [comment]
HA user is running under root, as such it should have all the rights it needs. Made the file executable regardless though (with the command line), but same error is still being outputted.

**Comment by Ernst79** [comment]
The python code is firing an "hciconfig" command. So, if that works from the command line (regardless of the folder you are in), than this should also work from python. 

You could try by changing it to the full path, to see if that is the issue. 

`output = subprocess.run(["/usr/bin/hciconfig"], stdout=subprocess.PIPE).stdout.decode("utf-8")`

**Comment by Skyridr** [comment]
That was worth a shot, but also a no go:

`FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/hciconfig'`

Same if I attempt to use sudo in the path.

**Comment by Magalex2x14** [comment]
@Skyridr how do you start HA (exactly command line)?
 If I understand correctly, the Snap-version of the HA is launched in some kind of a container on RPi... If this is the case, then there may be no access to the host shell?
https://github.com/home-assistant-snap/home-assistant-snap ("with LXD" section)

**Comment by Skyridr** [comment]
I've installed snap using the snap install command line rather than building/installing it manually. Not sure if LXD is being used though, as that appears to be empty.

```
root@Pi4:/home/skyrider# sudo lxc list
If this is your first time running LXD on this machine, you should also run: lxd init
To start your first instance, try: lxc launch ubuntu:18.04

+------+-------+------+------+------+-----------+
| NAME | STATE | IPV4 | IPV6 | TYPE | SNAPSHOTS |
+------+-------+------+------+------+-----------+
```

Though I do see tons of snap-lxd mounts in the systemd/system directory. According to the HA system file of snap:

```
# Auto-generated, DO NOT EDIT
Description=Service for snap application home-assistant-snap.home-assistant-snap
Requires=snap-home\x2dassistant\x2dsnap-285.mount
Wants=network.target
After=snap-home\x2dassistant\x2dsnap-285.mount network.target snapd.apparmor.service
X-Snappy=yes

[Service]
EnvironmentFile=-/etc/environment
ExecStart=/usr/bin/snap run home-assistant-snap
SyslogIdentifier=home-assistant-snap.home-assistant-snap
Restart=always
WorkingDirectory=/var/snap/home-assistant-snap/285
TimeoutStopSec=30
Type=simple

[Install]
WantedBy=multi-user.target
```

So maybe it is running inside some kind of container after all, using its own environment.

**Comment by Ernst79** [comment]
if pip requirements aren't installed, it is better to install without snap yes, as Home Assistant does depend on a lot of pip packages, every integration will often need some pip package, not only BLE monitor.

**Comment by Ernst79** [comment]
Closing this issue, feel free to reopen if you want to discuss further
