### ISSUE TITLE
LYWSD03MMC stop graph

### ISSUE THREAD

**Issue by azlux** [custom-components/ble_monitor#428]
Hi,
I'm using two LYWSD03MMC. Randomly the sensors stop getting updated.
My temperature and humidity say than last update is X hours ago.

I've enable ble debug logs.
I can see data from my sensors every 10s logged.

When it's work, I have this routine in my log every minutes (and all my sensors logs) : 
```
homeassistant        | 2021-07-05 18:10:35 DEBUG (MainThread) [custom_components.ble_monitor.binary_sensor] 9 MiBeacon BLE ADV messages processed for 0 binary sensor device(s) total. Priority queue = 0
homeassistant        | 2021-07-05 18:10:35 DEBUG (Thread-3) [custom_components.ble_monitor] HCIdump thread: main event_loop stopped, finishing
homeassistant        | 2021-07-05 18:10:35 DEBUG (MainThread) [custom_components.ble_monitor.sensor] 9 BLE ADV messages processed for 2 measuring device(s).
homeassistant        | 2021-07-05 18:10:35 DEBUG (Thread-3) [custom_components.ble_monitor] HCIdump thread: Scanning will be restarted
homeassistant        | 2021-07-05 18:10:35 DEBUG (Thread-3) [custom_components.ble_monitor] 63 HCI events processed for previous period.
homeassistant        | 2021-07-05 18:10:35 DEBUG (Thread-3) [custom_components.ble_monitor] HCIdump thread: Run
homeassistant        | 2021-07-05 18:10:35 DEBUG (Thread-3) [custom_components.ble_monitor] HCIdump thread: connected to hci0
homeassistant        | 2021-07-05 18:10:35 DEBUG (Thread-3) [custom_components.ble_monitor] HCIdump thread: start main event_loop
```

When the sensors are freezed, I only have every minutes (plus all my sensors data) : 
```
homeassistant        | 2021-07-05 18:14:36 DEBUG (MainThread) [custom_components.ble_monitor.binary_sensor] 10 MiBeacon BLE ADV messages processed for 0 binary sensor device(s) total. Priority queue = 0
```

Between both states, I have this error:
```
homeassistant        | 2021-07-05 18:11:18 DEBUG (MainThread) [custom_components.ble_monitor.sensor] Data measuring sensor received: {'temperature': 11.02, 'humidity': 158.72, 'voltage': 0.543, 'battery': 1, 'switch': 0, 'opening': 1, 'data': True, 'rssi': -99, 'mac': 'A4C138BF989$
', 'type': 'ATC', 'packet': 0, 'firmware': 'ATC (Custom)'}
homeassistant        | 2021-07-05 18:11:18 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
homeassistant        | Traceback (most recent call last):
homeassistant        |   File "/config/custom_components/ble_monitor/sensor.py", line 189, in async_run
homeassistant        |     entity.collect(data, batt_attr)
homeassistant        |   File "/config/custom_components/ble_monitor/sensor.py", line 592, in collect
homeassistant        |     if self._log_spikes:
homeassistant        | AttributeError: 'HumiditySensor' object has no attribute '_log_spikes'
homeassistant        | 2021-07-05 18:11:19 DEBUG (MainThread) [custom_components.ble_monitor.binary_sensor] Data binary sensor received: {'temperature': 20.09, 'humidity': 75.49, 'voltage': 2.929, 'battery': 81, 'switch': 1, 'opening': 0, 'data': True, 'rssi': -83, 'mac': 'A4C13840
7E21', 'type': 'ATC', 'packet': 29, 'firmware': 'ATC (Custom)'}
```

Thanks for your work. It's amazing
Best regards
Azlux

**Comment by Ernst79** [comment]
You can fix this by adding this line after line 579 in /ble_monitor/sensor.py (same indentation as the other lines,

`self._log_spikes = config[CONF_LOG_SPIKES]`

I will fix it in the next update

**Comment by azlux** [comment]
Thank for the help.
I've added the line.
