### ISSUE TITLE
errors after core upgrade

### ISSUE THREAD

**Issue by VerardoMatias** [custom-components/ble_monitor#458]
Hi! I installed a new version of hassio core and now the mijia sensors are not working.
When i restart the raspberry this notifications shows up.

```
Logger: homeassistant.setup
Source: setup.py:311
First occurred: 19:10:41 (1 occurrences)
Last logged: 19:10:41

Unable to prepare setup for platform ble_monitor.sensor: Platform not found (cannot import name 'VOLT' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).
```

////////////////////////////////////////////////////////////////

```
Logger: homeassistant.config_entries
Source: helpers/entity_component.py:181
First occurred: 19:22:04 (4 occurrences)
Last logged: 19:23:40

Error unloading entry Bluetooth Low Energy Monitor for sensor
Error unloading entry Bluetooth Low Energy Monitor for binary_sensor
Error unloading entry Bluetooth Low Energy Monitor for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 432, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 96, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
```

////////////////////////////////////////////////////////////////

```
## System Health

version | core-2021.8.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.6
os_name | Linux
os_version | 5.10.17-v7
arch | armv7l
timezone | America/Argentina/Buenos_Aires

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4933
Installed Version | 1.13.2
Stage | running
Available Repositories | 907
Installed Repositories | 5

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.2
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.8
docker_version | 20.10.6
disk_total | 28.6 GB
disk_used | 7.3 GB
healthy | true
supported | true
board | rpi3
supervisor_api | ok
version_api | ok
installed_addons | ESPHome (1.18.0), File editor (5.0.0), Node-RED (6.3.0), Samba share (9.2.0), Terminal & SSH (9.1.3), Spotify Connect (0.9.0), HassOS I2C Configurator (0.13)

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 0
views | 3
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>
```

**Comment by Ernst79** [comment]
Did you update ble monitor in HACS? This error should be already fixed.

**Comment by Ernst79** [comment]
Closing this issue, as it is already fixed. Feel free to reopen if you still have this issue
