### ISSUE TITLE
"Runtime error while sending scan request" after system upgrade

### ISSUE THREAD

**Issue by madarasz** [custom-components/ble_monitor#590]
I have a Home Assistant Core installation running on Raspberry Pi. Recently I wanted to upgrade to the latest Home Assistant Core and I had to do some other upgrades, I upped the OS to Raspbian GNU/Linux 11 (bullseye), Python to 3.9.5 and reinstalled the new 
"core-2021.12.5" HA Core. All is working fine since then, expect ble_monitor, which produces such errors every 2 minutes:
```
2021-12-27 08:40:34 ERROR (Thread-9) [custom_components.ble_monitor] HCIdump thread: Runtime error while sending scan request on hci0: Event loop stopped before Future completed.. Resetting Bluetooth adapter AA:AA:AA:AA:AA:AA and trying again.
2021-12-27 08:40:34 ERROR (Thread-9) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/ble_monitor/__init__.py", line 608, in run
    self._event_loop.run_until_complete(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 640, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/homeassistant/.homeassistant/custom_components/ble_monitor/__init__.py", line 619, in run
    reset_bluetooth(hci)
  File "/home/homeassistant/.homeassistant/custom_components/ble_monitor/bt_helpers.py", line 188, in reset_bluetooth
    rfkill_unblock_bluetooth()
  File "/home/homeassistant/.homeassistant/custom_components/ble_monitor/bt_helpers.py", line 84, in rfkill_unblock_bluetooth
    command = subprocess.run(["rfkill", "unblock", "bluetooth"], stderr=subprocess.PIPE, check=True)
  File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['rfkill', 'unblock', 'bluetooth']' returned non-zero exit status 1.
```

The Raspberry built-in bluetooth device seems to be working fine though: `hciconfig -a`
```
hci0:	Type: Primary  Bus: UART
	BD Address: AA:AA:AA:AA:AA:AA  ACL MTU: 1021:8  SCO MTU: 64:1
	UP RUNNING
	RX bytes:1994996 acl:30 sco:0 events:18061 errors:0
	TX bytes:104228 acl:30 sco:0 commands:7834 errors:0
	Features: 0xbf 0xfe 0xcf 0xfe 0xdb 0xff 0x7b 0x87
	Packet type: DM1 DM3 DM5 DH1 DH3 DH5 HV1 HV2 HV3
	Link policy: RSWITCH SNIFF
	Link mode: SLAVE ACCEPT
	Name: 'BlueZ 5.55'
	Class: 0x680000
	Service Classes: Capturing, Audio, Telephony
	Device Class: Miscellaneous,
	HCI Version: 4.1 (0x7)  Revision: 0x0
	LMP Version: 4.1 (0x7)  Subversion: 0x6119
	Manufacturer: Broadcom Corporation (15)
```
Also `bluetoothctl`; `scan on` spits out a nice device list, so bluetooth should be fine on an OS level.

How can I solve the ble_monitor problem? Am I missing a package? I have seen a similar bug with Hass.io install where downgrading Hass.io was the solution. I am using Home Assistant Core install and I want to use a recent version because of some new integrations. Thank you for the help in advance.

**Comment by Ernst79** [comment]
This error (and possible solutions) are described in the FAQ, https://custom-components.github.io/ble_monitor/faq#i-get-a-runtimeerror-event-loop-stopped-before-future-completed

My first guess is that in your case, you need to check step 4. 

I'm closing this topic, as this issue is already discussed in #295 If the FAQ doesn't solve your issue, please post your question in #295, to keep all information together
