### ISSUE TITLE
Errors when running BLE Monitor without BLE interface

### ISSUE THREAD

**Issue by Ernst79** [custom-components/ble_monitor#598]
When running BLE monitor without a BLE interface, e.g. with ESPHome forwarding the BLE advertisements to BLE monitor only, the following error is displayed continuously. 

HCIdump thread: OS error (hci0): [Errno 19] error while attempting to bind on interface 0: No such device
22:19:26 – (ERRO) Passive BLE monitor (custom integration) - mensagem ocorreu primeiro em 19:55:17 e repetiu-se 144 vezes.

This needs to be fixed somehow.

**Comment by andrewjswan** [comment]
Maybe:
```
ble_monitor:
  bt_interface:
    - none
```
?

**Comment by Ernst79** [comment]
yes, good idea. Didn't had time to look into it yet

**Comment by jpmassena** [comment]
Are you looking into this? 
You could allow a "none" interface (unchecked in the integrations UI) and then disable hardware scan when none was set?

**Comment by Ernst79** [comment]
Yes, I'm working on it at the moment. It's a bit more work than simply change it, as it is used at more than one location in the code. I'm also a bit busy coming week, as I'm selling my house, so I have limited access to a PC and have to do some other jobs in the house. So, it can take one or two weeks before I have something ready. But I have already made a start.

**Comment by Ernst79** [comment]
For the time being, you could look up the error text in the code and change `_LOGGER.error` to `_LOGGER.debug`.

https://github.com/custom-components/ble_monitor/blob/64f9cb064781c6ddc5089657d3710b31d10fe1ba/custom_components/ble_monitor/__init__.py#L599

**Comment by Ernst79** [comment]
First step done

- [x] Change the input

![image](https://user-images.githubusercontent.com/24375847/149549661-b65aacb4-8daf-4ac5-9dc6-70080af9c6c9.png)

The last option is in yaml 

```
ble_monitor:
  bt_interface: False
```

or 

```
ble_monitor:
  hci_interface: False
```

Default value (when you don't fill anything), will be the first hci number it can find, and if it can't find anything, it will be False. 

- [ ] Next step, make it stop scanning, when False

**Comment by Ernst79** [comment]
I have released 7.3.3-beta with an option to disable the Bluetooth interface, while still being able to use the parse service e.g. with ESPhome BLE gateway

**Comment by tunip** [comment]
Many thanks for this PR. From the UI I selected "Don't use Bluetooth adapter" and pressed "Submit", but a red error message was shown on the top (can't remember exactly, but something like this "Bluetooth interface with MAC address 00:00:00:00:00:00 is not available") and the configuration window stays open.

I changed it manually in the core.config_entries file in HA and then everything worked fine:
```
            {
                "entry_id": "d30216eefbc6f8d33468b6c3e444dda7",
                "version": 3,
                "domain": "ble_monitor",
                "title": "Bluetooth Low Energy Monitor",
                "data": {},
                "options": {
                    "bt_interface": [
                       "00:00:00:00:00:00" -> "disable" # changed it here manually to disable and then after HA restart it worked as expected
                    ],
                    "bt_auto_restart": false,
                    "active_scan": false,
                    "discovery": false,#
                   ...
```

**Comment by Ernst79** [comment]
Yes, that is a different bug I need to figure out. It looks like it checks for the old configuration format, while it should check the new format. I'll create an issue for that.

**Comment by Ernst79** [comment]
@tunip Fixed in 7.3.4-beta. It will change the config automagically from `"bt_interface": ["00:00:00:00:00:00"]` to `"bt_interface": ["disable"]`

**Comment by tunip** [comment]
@Ernst79 thanks for the fast fix. Currently, I have the following Home Assistant logs every few minutes with beta 7.3.4:
```
--- Logging error ---
Traceback (most recent call last):
  File "/config/custom_components/ble_monitor/__init__.py", line 627, in run
    mysocket[hci] = aiobs.create_bt_socket(hci)
  File "/usr/local/lib/python3.9/site-packages/aioblescan/aioblescan.py", line 1760, in create_bt_socket
    raise exceptions[0]
  File "/usr/local/lib/python3.9/site-packages/aioblescan/aioblescan.py", line 1690, in create_bt_socket
    sock = socket.socket(
  File "/usr/local/lib/python3.9/socket.py", line 232, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1432, in emit
    self.enqueue(self.prepare(record))
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1415, in prepare
    msg = self.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: %i format: a number is required, not str
Call stack:
  File "/usr/local/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/config/custom_components/ble_monitor/__init__.py", line 629, in run
    _LOGGER.error("HCIdump thread: OS error (hci%i): %s", hci, error)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1475, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/src/homeassistant/homeassistant/util/logging.py", line 51, in handle
    self.emit(record)
Message: 'HCIdump thread: OS error (hci%i): %s'
Arguments: ('disable', OSError(97, 'Address family not supported by protocol'))
--- Logging error ---
Traceback (most recent call last):
  File "/config/custom_components/ble_monitor/__init__.py", line 627, in run
    mysocket[hci] = aiobs.create_bt_socket(hci)
  File "/usr/local/lib/python3.9/site-packages/aioblescan/aioblescan.py", line 1760, in create_bt_socket
    raise exceptions[0]
  File "/usr/local/lib/python3.9/site-packages/aioblescan/aioblescan.py", line 1690, in create_bt_socket
    sock = socket.socket(
  File "/usr/local/lib/python3.9/socket.py", line 232, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: %i format: a number is required, not str
Call stack:
  File "/usr/local/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/config/custom_components/ble_monitor/__init__.py", line 629, in run
    _LOGGER.error("HCIdump thread: OS error (hci%i): %s", hci, error)
Message: 'HCIdump thread: OS error (hci%i): %s'
Arguments: ('disable', OSError(97, 'Address family not supported by protocol'))
```

Part of my core.config_entries after the device section:
```
         ],
                    "is_flow": true,
                    "hci_interface": [
                        "disable"
                    ]
                },
```

**Comment by Ernst79** [comment]
How did you configure BLE monitor? in YAML? 

Could you try with 5.3.5-beta (just released it)?

**Comment by tunip** [comment]
I configured it only via the UI (no YAML). On HA start this comes up only once with 7.3.5-beta:
```
  File "/config/custom_components/ble_monitor/__init__.py", line 641, in run
    mysocket[hci] = aiobs.create_bt_socket(hci)
  File "/usr/local/lib/python3.9/site-packages/aioblescan/aioblescan.py", line 1760, in create_bt_socket
    raise exceptions[0]
  File "/usr/local/lib/python3.9/site-packages/aioblescan/aioblescan.py", line 1690, in create_bt_socket
    sock = socket.socket(
  File "/usr/local/lib/python3.9/socket.py", line 232, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: %i format: a number is required, not str
Call stack:
  File "/usr/local/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/config/custom_components/ble_monitor/__init__.py", line 643, in run
    _LOGGER.error("HCIdump thread: OS error (hci%i): %s", hci, error)
Message: 'HCIdump thread: OS error (hci%i): %s'
Arguments: ('disable', OSError(97, 'Address family not supported by protocol'))
2022-01-23 20:57:35,040 - root - ERROR - Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1518, in _monitor
    self.handle(record)
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1499, in handle
    handler.handle(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 952, in handle
    self.emit(record)
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 191, in emit
    entry = LogEntry(record, stack, _figure_out_source(record, stack, self.hass))
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 98, in __init__
    self.message = deque([record.getMessage()], maxlen=5)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: %i format: a number is required, not str
```

If I open the configuration (nothing changed) and click submit the same traceback from [above](https://github.com/custom-components/ble_monitor/issues/598#issuecomment-1019550485) is shown.

And also every few minutes the traceback from [above](https://github.com/custom-components/ble_monitor/issues/598#issuecomment-1019550485).

I will try from scratch (delete integration, then add integration).

**Comment by Ernst79** [comment]
Can you show the entire core.config_entries?

**Comment by tunip** [comment]
The entire config:
```
            {
                "entry_id": "d30216eefbc6f8d33468b6c3e444dda7",
                "version": 4,
                "domain": "ble_monitor",
                "title": "Bluetooth Low Energy Monitor",
                "data": {},
                "options": {
                    "bt_interface": [
                        "disable"
                    ],
                    "bt_auto_restart": false,
                    "active_scan": false,
                    "discovery": false,
                    "period": 300,
                    "use_median": false,
                    "decimals": 0,
                    "log_spikes": false,
                    "restore_state": true,
                    "report_unknown": "Off",
                    "devices": [
                        {
                            "mac": "C4:7C:8D:6A:C3:F1",
                            "temperature_unit": "\u00b0C",
                            "decimals": "default",
                            "use_median": "default",
                            "restore_state": "default",
                            "reset_timer": 35,
                            "track_device": false,
                            "tracker_scan_interval": 20,
                            "consider_home": 180,
                            "delete device": false,
                            "name": "Bad Pflanze"
                        },
                        {
                            "mac": "C4:7C:8D:6B:56:B5",
                            "temperature_unit": "\u00b0C",
                            "decimals": "default",
                            "use_median": "default",
                            "restore_state": "default",
                            "reset_timer": 35,
                            "track_device": false,
                            "tracker_scan_interval": 20,
                            "consider_home": 180,
                            "delete device": false,
                            "name": "B\u00fcro Drachenbaum"
                        },
                        {
                            "mac": "C4:7C:8D:6B:35:AF",
                            "temperature_unit": "\u00b0C",
                            "decimals": "default",
                            "use_median": "default",
                            "restore_state": "default",
                            "reset_timer": 35,
                            "track_device": false,
                            "tracker_scan_interval": 20,
                            "consider_home": 180,
                            "delete device": false,
                            "name": "B\u00fcro Orchidee"
                        },
                        {
                            "mac": "A4:C1:38:07:E3:48",
                            "temperature_unit": "\u00b0C",
                            "decimals": 1,
                            "use_median": "default",
                            "restore_state": "default",
                            "reset_timer": 35,
                            "track_device": false,
                            "tracker_scan_interval": 20,
                            "consider_home": 180,
                            "delete device": false,
                            "name": "K\u00fcche Gefriertruhe"
                        },
                        {
                            "mac": "A4:C1:38:E6:40:3D",
                            "temperature_unit": "\u00b0C",
                            "decimals": 1,
                            "use_median": "default",
                            "restore_state": "default",
                            "reset_timer": 35,
                            "track_device": false,
                            "tracker_scan_interval": 20,
                            "consider_home": 180,
                            "delete device": false,
                            "name": "K\u00fcche K\u00fchlschrank"
                        },
                        {
                            "mac": "C4:7C:8D:6B:65:43",
                            "temperature_unit": "\u00b0C",
                            "decimals": "default",
                            "use_median": "default",
                            "restore_state": "default",
                            "reset_timer": 35,
                            "track_device": false,
                            "tracker_scan_interval": 20,
                            "consider_home": 180,
                            "delete device": false,
                            "name": "K\u00fcche Pflanze"
                        },
                        {
                            "mac": "C4:7C:8D:6A:B3:4F",
                            "temperature_unit": "\u00b0C",
                            "decimals": "default",
                            "use_median": "default",
                            "restore_state": "default",
                            "reset_timer": 35,
                            "track_device": false,
                            "tracker_scan_interval": 20,
                            "consider_home": 180,
                            "delete device": false,
                            "name": "K\u00fcche Orchidee"
                        },
                        {
                            "mac": "C4:7C:8D:6B:64:B1",
                            "temperature_unit": "\u00b0C",
                            "decimals": "default",
                            "use_median": "default",
                            "restore_state": "default",
                            "reset_timer": 35,
                            "track_device": false,
                            "tracker_scan_interval": 20,
                            "consider_home": 180,
                            "delete device": false,
                            "name": "Schlafzimmer Orchidee"
                        },
                        {
                            "mac": "C4:7C:8D:6A:C2:AF",
                            "temperature_unit": "\u00b0C",
                            "decimals": "default",
                            "use_median": "default",
                            "restore_state": "default",
                            "reset_timer": 35,
                            "track_device": false,
                            "tracker_scan_interval": 20,
                            "consider_home": 180,
                            "delete device": false,
                            "name": "Schlafzimmer Palme"
                        },
                        {
                            "mac": "C4:7C:8D:6A:C9:3F",
                            "temperature_unit": "\u00b0C",
                            "decimals": "default",
                            "use_median": "default",
                            "restore_state": "default",
                            "reset_timer": 35,
                            "track_device": false,
                            "tracker_scan_interval": 20,
                            "consider_home": 180,
                            "delete device": false,
                            "name": "WC Pflanze"
                        },
                        {
                            "mac": "C4:7C:8D:6B:40:85",
                            "temperature_unit": "\u00b0C",
                            "decimals": "default",
                            "use_median": "default",
                            "restore_state": "default",
                            "reset_timer": 35,
                            "track_device": false,
                            "tracker_scan_interval": 20,
                            "consider_home": 180,
                            "delete device": false,
                            "name": "Wohnbereich Orchidee"
                        },
                        {
                            "mac": "C4:7C:8D:6B:24:15",
                            "temperature_unit": "\u00b0C",
                            "decimals": "default",
                            "use_median": "default",
                            "restore_state": "default",
                            "reset_timer": 35,
                            "track_device": false,
                            "tracker_scan_interval": 20,
                            "consider_home": 180,
                            "delete device": false,
                            "name": "Wohnbereich Palme"
                        }
                    ],
                    "is_flow": true,
                    "hci_interface": [
                        "disable"
                    ]
                },
                "pref_disable_new_entities": false,
                "pref_disable_polling": false,
                "source": "user",
                "unique_id": "d30216eefbc6f8d33468b6c3e444dda7",
                "disabled_by": null
            },
```

**Comment by Ernst79** [comment]
Hmm, strange, it’s running the HCI scanner, while I (tried to) program it such that it wouldn’t start this process. I suspect that somehow a restart it called somewhere in the code. Could you check if this error shows up immediately after a restart, or that it takes a while ( how long)

**Comment by tunip** [comment]
Immediately after HA restart:
```
--- Logging error ---
Traceback (most recent call last):
  File "/config/custom_components/ble_monitor/__init__.py", line 641, in run
    mysocket[hci] = aiobs.create_bt_socket(hci)
  File "/usr/local/lib/python3.9/site-packages/aioblescan/aioblescan.py", line 1760, in create_bt_socket
    raise exceptions[0]
  File "/usr/local/lib/python3.9/site-packages/aioblescan/aioblescan.py", line 1690, in create_bt_socket
    sock = socket.socket(
  File "/usr/local/lib/python3.9/socket.py", line 232, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1432, in emit
    self.enqueue(self.prepare(record))
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1415, in prepare
    msg = self.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: %i format: a number is required, not str
Call stack:
  File "/usr/local/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/config/custom_components/ble_monitor/__init__.py", line 643, in run
    _LOGGER.error("HCIdump thread: OS error (hci%i): %s", hci, error)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1475, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/src/homeassistant/homeassistant/util/logging.py", line 51, in handle
    self.emit(record)
Message: 'HCIdump thread: OS error (hci%i): %s'
Arguments: ('disable', OSError(97, 'Address family not supported by protocol'))
--- Logging error ---
Traceback (most recent call last):
  File "/config/custom_components/ble_monitor/__init__.py", line 641, in run
    mysocket[hci] = aiobs.create_bt_socket(hci)
  File "/usr/local/lib/python3.9/site-packages/aioblescan/aioblescan.py", line 1760, in create_bt_socket
    raise exceptions[0]
  File "/usr/local/lib/python3.9/site-packages/aioblescan/aioblescan.py", line 1690, in create_bt_socket
    sock = socket.socket(
  File "/usr/local/lib/python3.9/socket.py", line 232, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol

During handling of the above exception, another exception occurred:

2022-01-23 21:34:15 ERROR (Thread-2) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1518, in _monitor
    self.handle(record)
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1499, in handle
    handler.handle(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 952, in handle
    self.emit(record)
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 191, in emit
    entry = LogEntry(record, stack, _figure_out_source(record, stack, self.hass))
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 98, in __init__
    self.message = deque([record.getMessage()], maxlen=5)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: %i format: a number is required, not str
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: %i format: a number is required, not str
Call stack:
  File "/usr/local/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/config/custom_components/ble_monitor/__init__.py", line 643, in run
    _LOGGER.error("HCIdump thread: OS error (hci%i): %s", hci, error)
Message: 'HCIdump thread: OS error (hci%i): %s'
Arguments: ('disable', OSError(97, 'Address family not supported by protocol'))
2022-01-23 21:34:15,881 - root - ERROR - Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1518, in _monitor
    self.handle(record)
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1499, in handle
    handler.handle(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 952, in handle
    self.emit(record)
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 191, in emit
    entry = LogEntry(record, stack, _figure_out_source(record, stack, self.hass))
  File "/usr/src/homeassistant/homeassistant/components/system_log/__init__.py", line 98, in __init__
    self.message = deque([record.getMessage()], maxlen=5)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: %i format: a number is required, not str
```

**Comment by Ernst79** [comment]
Could you enable debug logging (at debug level, see the faq how) for ble monitor and post the entire log? It might give me a clou why the HCIdump process starts.

**Comment by tunip** [comment]
The log with debug enabled:
https://zerobin.net/?60cb9625d67c9087#vRey7yWl6YjmXuT9616u35hidjZC1rm/NAvlIxj0P6E=

**Comment by Ernst79** [comment]
Thanks, I found the issue, will create a fix.

**Comment by Ernst79** [comment]
Can you check with 7.3.6-beta? Should be fixed now (hopefully)

**Comment by tunip** [comment]
different message now but every 1-2 seconds:
```
2022-01-23 22:42:45 ERROR (MainThread) [homeassistant.components.automation.esphome_ble_advertise] ESPHome BLE Advertise: Error executing script. Unexpected error for call_service at pos 1: 'NoneType' object has no attribute 'process_hci_events'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 381, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 584, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/ble_monitor/__init__.py", line 202, in service_parse_data
    await async_parse_data_service(hass, service_data)
  File "/config/custom_components/ble_monitor/__init__.py", line 461, in async_parse_data_service
    blemonitor.dumpt
hread.process_hci_events(
AttributeError: 'NoneType' object has no attribute 'process_hci_events'
2022-01-23 22:42:45 ERROR (MainThread) [homeassistant.components.automation.esphome_ble_advertise] While executing automation automation.esphome_ble_advertise
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 508, in async_trigger
    await self.action_script.async_run(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1260, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 880, in async_run
    await super().async_run()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 363, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 381, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 584, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/ble_monitor/__init__.py", line 202, in service_parse_data
    await async_parse_data_service(hass, service_data)
  File "/config/custom_components/ble_monitor/__init__.py", line 461, in async_parse_data_service
    blemonitor.dumpthread.process_hci_events(
AttributeError: 'NoneType' object has no attribute 'process_hci_events'
```

**Comment by Ernst79** [comment]
Ill look into it later today. Sorry for the inconvenience

**Comment by Ernst79** [comment]
Fingers crossed, but I think it is now fixed. 7.3.7-beta has been released. It works on my end, with the BT adapter disabled and sending data from the `services` tab in HA.

**Comment by tunip** [comment]
Many thanks for your support. I can confirm that it runs very well with 7.3.7-beta.
