### ISSUE TITLE
Fatal error: protocol.data_received() call failed. after updating to 6.7.1 from 6.7.0

### ISSUE THREAD

**Issue by stepanovdg** [custom-components/ble_monitor#612]
`
Error doing job: Fatal error: protocol.data_received() call failed.

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 870, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/config/deps/lib/python3.9/site-packages/aioblescan/aioblescan.py", line 1852, in data_received
    self.process(packet)
  File "/config/custom_components/ble_monitor/__init__.py", line 563, in process_hci_events
    sensor_msg, tracker_msg = self.ble_parser.parse_data(data)
  File "/config/custom_components/ble_monitor/ble_parser/__init__.py", line 141, in parse_data
    elif adstruct[0] == 0x11 and int(data[16:18].hex()) == 5183:
ValueError: invalid literal for int() with base 10: '1a02'
`

**Comment by Ernst79** [comment]
Fix is on its way, few minutes

**Comment by Ernst79** [comment]
Fixed in 6.7.2
