### ISSUE TITLE
configuration failed

### ISSUE THREAD

**Issue by floow77** [custom-components/ble_monitor#620]
Hello,
For lastest version, I have an error "configuration failed":

Log:
Cette erreur provient d'une intégration personnalisée
```

Logger: homeassistant.config_entries
Source: custom_components/ble_monitor/__init__.py:281
Integration: Passive BLE monitor (documentation, issues)
First occurred: 21:15:40 (1 occurrences)
Last logged: 21:15:40

Error setting up entry Bluetooth Low Energy Monitor for ble_monitor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/ble_monitor/__init__.py", line 281, in async_setup_entry
    list(BT_INTERFACES.values()).index(bt_mac)
ValueError: 'E4:5F:01:5E:79:40' is not in list
```

I tried to downgrade to v6.7.2 but error is still there.

**Comment by Ernst79** [comment]
This means that HA can’t find the Bluetooth adapter, did you change the BT interface?

**Comment by mbaumanndev** [comment]
Same issue on my side with version 6.8.0 on a fresh install on a RPI3

```
System Health

version: core-2021.12.8
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
user: root
virtualenv: false
python_version: 3.9.7
os_name: Linux
os_version: 5.10.63-v8
arch: aarch64
timezone: Europe/Paris


GitHub API: ok
Github API Calls Remaining: 4987
Installed Version: 1.19.2
Stage: running
Available Repositories: 930
Downloaded Repositories: 2


logged_in: false
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: failed to load: timeout


host_os: Home Assistant OS 7.1
update_channel: stable
supervisor_version: supervisor-2021.12.2
docker_version: 20.10.9
disk_total: 29.0 GB
disk_used: 3.0 GB
healthy: true
supported: true
board: rpi3-64
supervisor_api: ok
version_api: ok
installed_addons: File editor (5.3.3), AirCast (3.2.1), Samba Backup (5.0.0), Terminal & SSH (9.3.0)


dashboards: 1
resources: 0
mode: auto-gen
```

**Comment by floow77** [comment]
> This means that HA can’t find the Bluetooth adapter, did you change the BT interface?

no change (I have a rpi4)

**Comment by Ernst79** [comment]
Did you upgrade HA OS recently? If so, try a full system reboot, not only restart HA, but the entire system

**Comment by mbaumanndev** [comment]
On my side a reboot of the system helped, thanks !

**Comment by floow77** [comment]
> Did you upgrade HA OS recently? If so, try a full system reboot, not only restart HA, but the entire system

thanks a lot, a reboot of the system resolved my issue.

**Comment by Ernst79** [comment]
Just to explain what happens, during the HA Os update, some Bluetooth things (software/firmware) could have been updated. Sometimes, the system becomes a bit messed up, a restart normally helps in that case.

**Comment by floow77** [comment]
ok, thanks for explanation
