### ISSUE TITLE
KeyError: 9

### ISSUE THREAD

**Issue by aletzi1** [custom-components/ble_monitor#632]
HACS: 1.19.3
BLE: 7.0.1
Core: 2021.12.9

Logger: homeassistant
Source: custom_components/ble_monitor/ble_parser/oral_b.py:75
Integration: Passive BLE monitor (documentation, issues)
First occurred: 22.02.49 (1 occurrences)
Last logged: 22.02.49

Error doing job: Fatal error: protocol.data_received() call failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 870, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.9/site-packages/aioblescan/aioblescan.py", line 1855, in data_received
    self.process(packet)
  File "/config/custom_components/ble_monitor/__init__.py", line 563, in process_hci_events
    sensor_msg, tracker_msg = self.ble_parser.parse_data(data)
  File "/config/custom_components/ble_monitor/ble_parser/__init__.py", line 199, in parse_data
    sensor_data = parse_oral_b(self, man_spec_data, mac, rssi)
  File "/config/custom_components/ble_monitor/ble_parser/oral_b.py", line 75, in parse_oral_b
    "sector": SECTORS[sector],
KeyError: 9

Hope this helps!

**Comment by Ernst79** [comment]
Could you please try with 7.1.1-beta

**Comment by aletzi1** [comment]
I think its fixed. Thanks 👍🏻
