### ISSUE TITLE
Bluetooth dongle not recognized with newest update

### ISSUE THREAD

**Issue by permissionBRICK** [custom-components/ble_monitor#709]
I updated to 7.6.0, and was greeted with all BLE sensors no longer working, it turns out the Integration fails to discover my BLE stick.
![image](https://user-images.githubusercontent.com/40219477/153661769-4617a722-2818-4fb4-9469-6320f715136e.png)

```
2022-02-11 20:51:03 WARNING (MainThread) [custom_components.ble_monitor.bt_helpers] hci%i has no (or disabled) BT LE capabilities.
2022-02-11 20:51:04 ERROR (MainThread) [custom_components.ble_monitor] Bluetooth adapter with MAC address ['XX:XX:XX:XX:XX:XX'] was not found. It is therefore changed back to the default adapter. Check the BLE monitor settings, if needed.
2022-02-11 20:51:04 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Bluetooth Low Energy Monitor for ble_monitor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 327, in async_setup
result = await component.async_setup_entry(hass, self)
File "/config/custom_components/ble_monitor/__init__.py", line 371, in async_setup_entry
list(BT_INTERFACES.values()).index(DEFAULT_BT_INTERFACE)
ValueError: 'disable' is not in list
```
Restarting HA or even the Host PC does not help the situation. I am Running HA Docker on Unraid, and am running the Container in privileged mode to pass through the BLE stick.
lsusb does show the device on the host, as well as inside HA:
Bus 001 Device 002: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)

I downgraded to 7.5.2 and it is working again.

**Comment by Magalex2x14** [comment]
Hello! Can you, please, install 7.6.0 and enable [debug logging](https://custom-components.github.io/ble_monitor/faq#debug), and throw here everything that appears in the log before the error since the start of HA.

It would also be useful to see the output of the `sudo btmgmt info` command on your host.

**Comment by permissionBRICK** [comment]
Here you go

```
2022-02-11 23:29:30 DEBUG (MainThread) [custom_components.ble_monitor.bt_helpers] Response(header=<event_code=CommandCompleteEvent, controller_idx=0, param_len=283>, event_frame=<command_opcode=ReadControllerInformation, status=Success>, cmd_response_frame=<address=XX:XX:XX:XX:XX:XX, bluetooth_version=6, manufacturer=10, supported_settings=114687, current_settings={Powered: True, Connectable: False, FastConnectable: False, Discoverable: False, Bondable: False, LinkLevelSecurity: False, SecureSimplePairing: False, BREDR: True, HighSpeed: False, LowEnergy: False, Advertising: False, SecureConnections: False, DebugKeys: False, Privacy: False, ControllerConfiguration: False, StaticAddress: False, PHYConfiguration: False, WidebandSpeech: False}, class_of_device=0, name=b'TP-Link Bluetooth Adapter', short_name=0>)
2022-02-11 23:29:30 WARNING (MainThread) [custom_components.ble_monitor.bt_helpers] hci%i has no (or disabled) BT LE capabilities.
2022-02-11 23:29:30 DEBUG (MainThread) [custom_components.ble_monitor.bt_helpers] No Bluetooth LE adapter found. Make sure Bluetooth is installed on your system.
2022-02-11 23:29:30 DEBUG (MainThread) [custom_components.ble_monitor] Initializing BLE Monitor entry (config entry): <homeassistant.config_entries.ConfigEntry object at 0x147bd61e2250>
2022-02-11 23:29:30 DEBUG (MainThread) [custom_components.ble_monitor] async_setup_entry: domain {}
2022-02-11 23:29:30 ERROR (MainThread) [custom_components.ble_monitor] Bluetooth adapter with MAC address ['XX:XX:XX:XX:XX:XX'] was not found. It is therefore changed back to the default adapter. Check the BLE monitor settings, if needed.
2022-02-11 23:29:30 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Bluetooth Low Energy Monitor for ble_monitor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 327, in async_setup
result = await component.async_setup_entry(hass, self)
File "/config/custom_components/ble_monitor/__init__.py", line 371, in async_setup_entry
list(BT_INTERFACES.values()).index(DEFAULT_BT_INTERFACE)
ValueError: 'disable' is not in list
```

Also i dont have btmgmt on unraid or HA, but here is some hciconfig if that helps (i keep censoring the mac, just to avoid confusion)

```
        hci0:   Type: Primary  Bus: USB
        BD Address: XX:XX:XX:XX:XX:XX  ACL MTU: 310:10  SCO MTU: 64:8
        HCI Version: 4.0 (0x6)  Revision: 0x22bb
        LMP Version: 4.0 (0x6)  Subversion: 0x22bb
        Manufacturer: Cambridge Silicon Radio (10)
```

**Comment by permissionBRICK** [comment]
Oh yeah, and heres this>
```
hciconfig hci0 lestates
Supported link layer states:
        YES Non-connectable Advertising State
        YES Scannable Advertising State
        YES Connectable Advertising State
        YES Directed Advertising State
        YES Passive Scanning State
        YES Active Scanning State
        YES Initiating State/Connection State in Master Role
        YES Connection State in the Slave Role
        YES Non-connectable Advertising State and Passive Scanning State combination
        YES Scannable Advertising State and Passive Scanning State combination
        YES Connectable Advertising State and Passive Scanning State combination
        YES Directed Advertising State and Passive Scanning State combination
        YES Non-connectable Advertising State and Active Scanning State combination
        YES Scannable Advertising State and Active Scanning State combination
        YES Connectable Advertising State and Active Scanning State combination
        YES Directed Advertising State and Active Scanning State combination
        YES Non-connectable Advertising State and Initiating State combination
        YES Scannable Advertising State and Initiating State combination
        YES Non-connectable Advertising State and Master Role combination
        YES Scannable Advertising State and Master Role combination
        YES Non-connectable Advertising State and Slave Role combination
        YES Scannable Advertising State and Slave Role combination
        YES Passive Scanning State and Initiating State combination
        YES Active Scanning State and Initiating State combination
        YES Passive Scanning State and Master Role combination
        YES Active Scanning State and Master Role combination
        YES Passive Scanning State and Slave Role combination
        YES Active Scanning State and Slave Role combination
        YES Initiating State and Master Role combination/Master Role and Master Role combination
```

**Comment by Magalex2x14** [comment]
Thank you!
It looks like `LowEnergy: False` in current adapter settings does not indicate the impossibility of LE scanning.
Soon I will remove this check, and make a release with a fix.

**Comment by Magalex2x14** [comment]
7.6.1 released. I'll try to figure out if this is some kind of a bug, or I misunderstand the value of "LowEnergy" setting...
