### ISSUE TITLE
protocol.data_received() call failed

### ISSUE THREAD

**Issue by edgarvoorbraak** [custom-components/ble_monitor#757]
I have this error on the latest build, 7.9.3.
It causes the whole integration to stop working basically.

Logger: homeassistant
Source: custom_components/ble_monitor/ble_parser/__init__.py:273
Integration: Passive BLE monitor (documentation, issues)
First occurred: 01:05:11 (1077 occurrences)
Last logged: 19:05:18

Error doing job: Fatal error: protocol.data_received() call failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 870, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.9/site-packages/aioblescan/aioblescan.py", line 1855, in data_received
    self.process(packet)
  File "/config/custom_components/ble_monitor/__init__.py", line 648, in process_hci_events
    sensor_msg, tracker_msg = self.ble_parser.parse_data(data)
  File "/config/custom_components/ble_monitor/ble_parser/__init__.py", line 273, in parse_data
    elif ((man_spec_data[4] << 8) | man_spec_data[5]) == 0xBEAC and data_len == 0x1B:
IndexError: index out of range

**Comment by Ernst79** [comment]
Please try 7.9.4, I think this version will fix your issue.

Let me know if it is fixed

**Comment by edgarvoorbraak** [comment]
Awesome, that fixed it, thanks.
