### ISSUE TITLE
Fatal error: protocol.data_received() call failed

### ISSUE THREAD

**Issue by ACrazyConcept** [custom-components/ble_monitor#771]
I get this error once in a while. I do have an oral b toothbrush. But I also get the error even if the toothbrush is not defined under devices.

Config with version 7.9.6
```
ble_monitor:
  bt_interface:
    - '00:1A:7D:DA:71:16'
    - 'B8:27:EB:B0:86:E6'
  discovery: False
  active_scan: False
  report_unknown: False
  decimals: 2
  log_spikes: False
  use_median: True
  restore_state: True
  devices:
    - mac: '7C:01:0A:46:56:0C'
```

```
2022-03-10 12:38:32 ERROR (Thread-3) [homeassistant] Error doing job: Fatal error: protocol.data_received() call failed.
Traceback (most recent call last):
File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 870, in _read_ready__data_received
self._protocol.data_received(data)
File "/usr/local/lib/python3.9/site-packages/aioblescan/aioblescan.py", line 1855, in data_received
self.process(packet)
File "/config/custom_components/ble_monitor/__init__.py", line 648, in process_hci_events
sensor_msg, tracker_msg = self.ble_parser.parse_data(data)
File "/config/custom_components/ble_monitor/ble_parser/__init__.py", line 195, in parse_data
sensor_data = parse_oral_b(self, man_spec_data, mac, rssi)
File "/config/custom_components/ble_monitor/ble_parser/oral_b.py", line 59, in parse_oral_b
"toothbrush state": STATES[state],
KeyError: 8
2022-03-10 12:38:36 ERROR (Thread-3) [homeassistant] Error doing job: Fatal error: protocol.data_received() call failed.
Traceback (most recent call last):
File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 870, in _read_ready__data_received
self._protocol.data_received(data)
File "/usr/local/lib/python3.9/site-packages/aioblescan/aioblescan.py", line 1855, in data_received
self.process(packet)
File "/config/custom_components/ble_monitor/__init__.py", line 648, in process_hci_events
sensor_msg, tracker_msg = self.ble_parser.parse_data(data)
File "/config/custom_components/ble_monitor/ble_parser/__init__.py", line 195, in parse_data
sensor_data = parse_oral_b(self, man_spec_data, mac, rssi)
File "/config/custom_components/ble_monitor/ble_parser/oral_b.py", line 59, in parse_oral_b
"toothbrush state": STATES[state],
KeyError: 8
```

When the toothbrush is configured it appears like this:
![image](https://user-images.githubusercontent.com/36438756/157721679-a1be7855-09b6-4ba5-a94a-7699cf84e6f4.png)

**Comment by Ernst79** [comment]
A fix is on its way in the next release. 

A state = `8` has been send by the toothbrush, but we only have defined state numbers 0-6 and 113-116. All others will cause the error you have. I changed it such that it now sets the state to "unknown state 8", instead of causing a `Fatal Error`. 

In case you know the meaning of this state 8, let us know, such that we can add it.

**Comment by ACrazyConcept** [comment]
Thanks @Ernst79 
I don't know what it means. I don't even know where to start looking. But if you have a suggestion to get me started I can try.

**Comment by Ernst79** [comment]
I think just by trial and error. With the new version, you will sometimes see "unknown state 8" as the toothbrush_state.

![image](https://user-images.githubusercontent.com/24375847/157830967-898b3809-4ef4-48df-9cda-96092eb8da8f.png)

Perhaps this corresponds to a certain handling you do at that moment. For you info, these are the other states we do know the meaning of. state 8 should be something similar. 

```
STATES = {
    0: "unknown",
    1: "initializing",
    2: "idle",
    3: "running",
    4: "charging",
    5: "setup",
    6: "flight menu",
    113: "final test",
    114: "pcb test",
    115: "sleeping",
    116: "transport"
}
```
