### ISSUE TITLE
[Bug]: Error cgpr1 binary sensor motion detect

### ISSUE THREAD

**Issue by e1evat** [custom-components/ble_monitor#781]
### What happened?

With Version 8.1.0 I get the following error for my cgpr1 when motion is detected.
With Version 7.9.7 everything worked well. Very similar to the issue #739

### Sensor type

cgpr1

### Relevant log output

```shell
2022-03-18 22:07:28 ERROR (MainThread) [homeassistant.helpers.entity] Update for binary_sensor.ble_motion_582d34609aca fails
Traceback (most recent call last):
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 535, in async_update_ha_state
    await self.async_device_update()
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 744, in async_device_update
    raise exc
  File "/opt/homeassistant/config/custom_components/ble_monitor/binary_sensor.py", line 497, in async_update
  File "/opt/homeassistant/lib/python3.9/site-packages/homeassistant/util/dt.py", line 125, in parse_datetime
    return ciso8601.parse_datetime(dt_str)
TypeError: argument 1 must be str, not datetime.datetime
```

**Comment by Ernst79** [comment]
Fixed in 8.1.1
