### ISSUE TITLE
[Bug]:  custom_components/ble_monitor/ble_parser/xiaogui.py:46 

### ISSUE THREAD

**Issue by ingo01978** [custom-components/ble_monitor#824]
### What happened?

Logger: custom_components.ble_monitor.ble_parser.xiaogui
Source: custom_components/ble_monitor/ble_parser/xiaogui.py:46 
Integration: Passive BLE monitor ([documentation](https://github.com/custom-components/ble_monitor), [issues](https://github.com/custom-components/ble_monitor/issues)) 
First occurred: 08:35:18 (366 occurrences) 
Last logged: 09:00:46

Stabilized byte of Xiaogui scale is reporting a new value, please report an issue to the developers with this error: Payload is 10ffc022000000000a01247014f60765ec
Stabilized byte of Xiaogui scale is reporting a new value, please report an issue to the developers with this error: Payload is 10ffc0c3000000000a01247014f60765ec
Stabilized byte of Xiaogui scale is reporting a new value, please report an issue to the developers with this error: Payload is 10ffc0d2000000000a01247014f60765ec
Stabilized byte of Xiaogui scale is reporting a new value, please report an issue to the developers with this error: Payload is 10ffc0592c4700000a01247014f60765ec
Stabilized byte of Xiaogui scale is reporting a new value, please report an issue to the developers with this error: Payload is 10ffc07d2c4700000a01257014f60765ec

### Sensor type

Xiaogui scale

### Relevant log output

```shell
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.ble_monitor.ble_parser.xiaogui
Source: custom_components/ble_monitor/ble_parser/xiaogui.py:46 
Integration: Passive BLE monitor (documentation, issues) 
First occurred: 08:35:18 (366 occurrences) 
Last logged: 09:00:46

Stabilized byte of Xiaogui scale is reporting a new value, please report an issue to the developers with this error: Payload is 10ffc022000000000a01247014f60765ec
Stabilized byte of Xiaogui scale is reporting a new value, please report an issue to the developers with this error: Payload is 10ffc0c3000000000a01247014f60765ec
Stabilized byte of Xiaogui scale is reporting a new value, please report an issue to the developers with this error: Payload is 10ffc0d2000000000a01247014f60765ec
Stabilized byte of Xiaogui scale is reporting a new value, please report an issue to the developers with this error: Payload is 10ffc0592c4700000a01247014f60765ec
Stabilized byte of Xiaogui scale is reporting a new value, please report an issue to the developers with this error: Payload is 10ffc07d2c4700000a01257014f60765ec
```

**Comment by Ernst79** [comment]
Interesting, So far, we have seen `stabilized byte` = 20 for non stabilized measurements and 21 for stabilized measurements. 

We now have `stabilized byte` = 24 and 25. 24 seems to be non-stabilized measurements, 25 stabilized measurements. The data I get is 11335. In the old situation, we had to divide this value with 10 to get the weight. 

Possibly changed to "divide by 100"? 11335 / 100 = 113.35 kg? Can that be correct?

**Comment by ingo01978** [comment]
Hello, yes that can be true.

**Comment by Ernst79** [comment]
Ok, and do you own a Xiaogui TZC4, or a different type?

**Comment by ingo01978** [comment]
No, that's not a Xiaogui TZC4! This scale is from MaxxMee Mod: QJ-J and should be identical to that of Xiaogui. The two scales use the same app. this is the OkOK app.

**Comment by Ernst79** [comment]
Ok, one last question, does ble monitor work for this scale, despite the errors in the log? Does it update the weight etc.?

**Comment by ingo01978** [comment]
Hello, with the Gtags everything works as usual and with the scales I can't say if it works yet. Since, as in the post, the error message comes and the values ​​are not filled. But after you fit the calculated values. By the way, the scale shows the value for the weight and the resistance. If you want I can also send pictures.

**Comment by ingo01978** [comment]
I just got the BLEMonitor update. Now it shows me a weight, but this weight is wrong.

**Comment by ingo01978** [comment]
![DB668989-EC34-4CC4-97DE-E725ED33DBBF](https://user-images.githubusercontent.com/33171238/162674061-76d09e36-6642-4b10-97f3-97cad06a7509.png)

**Comment by ingo01978** [comment]
![image](https://user-images.githubusercontent.com/33171238/162674189-f88f0aa8-4375-4978-b4f2-cd863bd318e0.jpg)

**Comment by Ernst79** [comment]
Hmmm, that means that is also sends messages with 0x20 and 0x21 (besides the 0x24 and 0x25). I was hoping it was only sending the last two, which could make it easier to program it as two different devices. We have two options, I guess.

I will make a test version, with some logging, to get a the messages. I need to figure out how to distinguish between the two scale measurements, or how to rule out the 0x20 and 0x21 messages for your scale.

**Comment by Ernst79** [comment]
Can you try the following. Replace the content of `custom_components/ble_monitor/ble_parser/xiaogui.py` with the code from this modified file. 

https://github.com/custom-components/ble_monitor/blob/QJ-J/custom_components/ble_monitor/ble_parser/xiaogui.py

After that, enable debug logging for BLE monitor at info level with the following config.

```yaml
logger:
  default: warn
  logs:
    custom_components.ble_monitor: info
```

Restart HA, 
Collect the messages in the HA logs after a weight session and post them here. Please also check the impedance.

**Comment by ingo01978** [comment]
I have made. And no change in Weight and Impedance.

Logger: homeassistant.components.automation.esphome_ble_advertise
Source: custom_components/ble_monitor/__init__.py:665 
Integration: Automatisierung (documentation, issues) 
First occurred: 08:54:08 (2 occurrences) 
Last logged: 08:54:08

087 ESPHome BLE Advertise: Error executing script. Unexpected error for call_service at pos 1: 'type'
While executing automation automation.esphome_ble_advertise
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 379, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 582, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1634, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1671, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/ble_monitor/__init__.py", line 209, in service_parse_data
    await async_parse_data_service(hass, service_data)
  File "/config/custom_components/ble_monitor/__init__.py", line 501, in async_parse_data_service
    blemonitor.dumpthread.process_hci_events(
  File "/config/custom_components/ble_monitor/__init__.py", line 665, in process_hci_events
    device_type = sensor_msg["type"]
KeyError: 'type'

**Comment by Ernst79** [comment]
Sorry, my mistake. Can you try again, I just updated the file to fix this

**Comment by ingo01978** [comment]
No problem!
Great success. The Weight is displayed correctly. The Impedance is at 600 Ohm. I tried this with two people. There is no entry in the log. Thank you for the quick help and the BLE monitor.

**Comment by Ernst79** [comment]
are you sure you don't get messages in the log? You will need to look in the full home assistant log, by clicking this button

![image](https://user-images.githubusercontent.com/24375847/162703848-7e533a37-21b0-43a9-925a-574421d890dc.png)

**Comment by ingo01978** [comment]
Oh sorry...

2022-04-11 12:25:17 INFO (MainThread) [custom_components.ble_monitor] Attention! Option report_unknown is enabled for sensor with id(s): ['7014F60765EC']
2022-04-11 12:26:46 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x24 advertisement with data 10ffc0a72c1500000a01247014f60765ec and control 2561
2022-04-11 12:26:46 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc0a72c1500000a01247014f60765ecaf
2022-04-11 12:26:49 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x25 advertisement with data 10ffc09e2c1500000a01257014f60765ec and control 2561
2022-04-11 12:26:49 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc09e2c1500000a01257014f60765ecb0
2022-04-11 12:26:52 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x25 advertisement with data 10ffc09e2c1500000a01257014f60765ec and control 2561
2022-04-11 12:26:52 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc09e2c1500000a01257014f60765ecb1
2022-04-11 12:26:56 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x25 advertisement with data 10ffc09e2c1500000a01257014f60765ec and control 2561
2022-04-11 12:26:56 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc09e2c1500000a01257014f60765ecb1

**Comment by Ernst79** [comment]
Can you make a longer log. I want to know if it ever shows 0x20 and/or 0x21. Let it run for a few hours.

**Comment by ingo01978** [comment]
Hello, here is the log from several hours.

2022-04-11 17:20:27 INFO (MainThread) [custom_components.ble_monitor] Attention! Option report_unknown is enabled for sensor with id(s): ['7014F60765EC']

2022-04-11 19:02:41 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x25 advertisement with data 10ffc09f2c3d00000a01257014f60765ec and control 2561
2022-04-11 19:02:41 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc09f2c3d00000a01257014f60765ecad
2022-04-11 19:02:43 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x25 advertisement with data 10ffc09f2c3d00000a01257014f60765ec and control 2561
2022-04-11 19:02:43 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc09f2c3d00000a01257014f60765ecac
2022-04-11 19:02:47 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x25 advertisement with data 10ffc09f2c3d00000a01257014f60765ec and control 2561
2022-04-11 19:02:47 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc09f2c3d00000a01257014f60765ecb4
2022-04-11 19:02:50 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x25 advertisement with data 10ffc09f2c3d00000a01257014f60765ec and control 2561
2022-04-11 19:02:50 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc09f2c3d00000a01257014f60765ecb3
2022-04-11 19:02:51 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x25 advertisement with data 10ffc09f2c3d00000a01257014f60765ec and control 2561
2022-04-11 19:02:51 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc09f2c3d00000a01257014f60765ecae
2022-04-11 19:02:58 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x24 advertisement with data 10ffc024000000000a01247014f60765ec and control 2561
2022-04-11 19:02:58 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc024000000000a01247014f60765ecab
2022-04-11 19:03:01 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x24 advertisement with data 10ffc06f000000000a01247014f60765ec and control 2561
2022-04-11 19:03:01 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc06f000000000a01247014f60765ecac
2022-04-11 19:03:07 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x24 advertisement with data 10ffc03d000000000a01247014f60765ec and control 2561
2022-04-11 19:03:07 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc03d000000000a01247014f60765ecae
2022-04-11 19:03:09 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x24 advertisement with data 10ffc05c000000000a01247014f60765ec and control 2561
2022-04-11 19:03:09 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc05c000000000a01247014f60765ecad
2022-04-11 19:03:13 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x24 advertisement with data 10ffc0e6000000000a01247014f60765ec and control 2561
2022-04-11 19:03:13 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc0e6000000000a01247014f60765ecac
2022-04-11 19:03:17 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x24 advertisement with data 10ffc0b5000000000a01247014f60765ec and control 2561
2022-04-11 19:03:17 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 04


2022-04-12 06:53:50 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x25 advertisement with data 10ffc0a0284100000a01257014f60765ec and control 2561
2022-04-12 06:53:50 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc0a0284100000a01257014f60765ecb1
2022-04-12 06:53:51 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x25 advertisement with data 10ffc0a0284100000a01257014f60765ec and control 2561
2022-04-12 06:53:51 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc0a0284100000a01257014f60765ecb0
2022-04-12 06:53:52 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x25 advertisement with data 10ffc0a0284100000a01257014f60765ec and control 2561
2022-04-12 06:53:52 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc0a0284100000a01257014f60765ecb1
2022-04-12 06:53:53 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x25 advertisement with data 10ffc0a0284100000a01257014f60765ec and control 2561
2022-04-12 06:53:53 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc0a0284100000a01257014f60765ecb5
2022-04-12 06:53:54 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x25 advertisement with data 10ffc0a0284100000a01257014f60765ec and control 2561
2022-04-12 06:53:54 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc0a0284100000a01257014f60765ecb5
2022-04-12 06:53:54 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x25 advertisement with data 10ffc0a0284100000a01257014f60765ec and control 2561
2022-04-12 06:53:54 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc0a0284100000a01257014f60765ecb6
2022-04-12 06:53:58 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x25 advertisement with data 10ffc0a0284100000a01257014f60765ec and control 2561
2022-04-12 06:53:58 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc0a0284100000a01257014f60765ecb1
2022-04-12 06:54:00 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x25 advertisement with data 10ffc0a0284100000a01257014f60765ec and control 2561
2022-04-12 06:54:00 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc0a0284100000a01257014f60765ecb5
2022-04-12 06:54:16 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x24 advertisement with data 10ffc0f4000000000a01247014f60765ec and control 2561
2022-04-12 06:54:16 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc0f4000000000a01247014f60765ecb5
2022-04-12 06:54:21 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x24 advertisement with data 10ffc002000000000a01247014f60765ec and control 2561
2022-04-12 06:54:21 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc002000000000a01247014f60765ecb4
2022-04-12 06:54:23 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x24 advertisement with data 10ffc043000000000a01247014f60765ec and control 2561
2022-04-12 06:54:23 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc043000000000a01247014f60765ecb4
2022-04-12 06:54:25 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x24 advertisement with data 10ffc0bd000000000a01247014f60765ec and control 2561
2022-04-12 06:54:25 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc0bd000000000a01247014f60765ecb4

2022-04-12 07:06:30 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x24 advertisement with data 10ffc0d62c1500000a01247014f60765ec and control 2561
2022-04-12 07:06:30 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc0d62c1500000a01247014f60765ecb3
2022-04-12 07:06:34 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x25 advertisement with data 10ffc0a12c1500000a01257014f60765ec and control 2561
2022-04-12 07:06:34 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc0a12c1500000a01257014f60765ecb2

2022-04-12 07:06:40 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x25 advertisement with data 10ffc0a12c1500000a01257014f60765ec and control 2561
2022-04-12 07:06:40 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc0a12c1500000a01257014f60765ecae
2022-04-12 07:06:46 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x24 advertisement with data 10ffc0a8000000000a01247014f60765ec and control 2561
2022-04-12 07:06:46 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc0a8000000000a01247014f60765ecb0
2022-04-12 07:06:51 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x24 advertisement with data 10ffc0dd000000000a01247014f60765ec and control 2561
2022-04-12 07:06:51 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc0dd000000000a01247014f60765ecb0
2022-04-12 07:06:55 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x24 advertisement with data 10ffc02a000000000a01247014f60765ec and control 2561
2022-04-12 07:06:55 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc02a000000000a01247014f60765ecb0
2022-04-12 07:06:57 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x24 advertisement with data 10ffc02a000000000a01247014f60765ec and control 2561
2022-04-12 07:06:57 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc02a000000000a01247014f60765ecb0
2022-04-12 07:07:01 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x24 advertisement with data 10ffc08f000000000a01247014f60765ec and control 2561
2022-04-12 07:07:01 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc08f000000000a01247014f60765ecb0
2022-04-12 07:07:02 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x24 advertisement with data 10ffc0ab000000000a01247014f60765ec and control 2561
2022-04-12 07:07:02 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc0ab000000000a01247014f60765ecb0
2022-04-12 07:07:03 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x24 advertisement with data 10ffc0a8000000000a01247014f60765ec and control 2561
2022-04-12 07:07:03 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc0a8000000000a01247014f60765ecb0
2022-04-12 07:07:04 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x24 advertisement with data 10ffc094000000000a01247014f60765ec and control 2561
2022-04-12 07:07:04 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc094000000000a01247014f60765ecb0
2022-04-12 07:07:06 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x24 advertisement with data 10ffc070000000000a01247014f60765ec and control 2561
2022-04-12 07:07:06 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc070000000000a01247014f60765ecb1
2022-04-12 07:07:07 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x24 advertisement with data 10ffc054000000000a01247014f60765ec and control 2561
2022-04-12 07:07:07 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc054000000000a01247014f60765ecaf
2022-04-12 07:07:08 INFO (MainThread) [custom_components.ble_monitor.ble_parser.xiaogui] 0x24 advertisement with data 10ffc045000000000a01247014f60765ec and control 2561
2022-04-12 07:07:08 INFO (MainThread) [custom_components.ble_monitor.ble_parser] BLE advertisement received from MAC/UUID 7014f60765ec: 043e1d02010300ec6507f614701110ffc045000000000a01247014f60765ecb0

**Comment by Ernst79** [comment]
hmm, ok. All 0x24 and 0x25. The strange thing is that you mentioned that you had a weight measurement once, before the change. We might also use the "control" number. For the previous scale, it was also a constant value `0002`. Hopefully, this is an indicator for the device (brand). I'll create a PR and we will see how it goes.

**Comment by ingo01978** [comment]
Right, that's strange. I just got a thought. Before the change, I had built a function that made it possible to assign different weights to 3 people. It may be that I set the sensor to the value manually! I think that's how it was. Because nobody here weighs exactly 80 kilos.

**Comment by Ernst79** [comment]
I will release it in 8.6.1 within one hour. However, the device will be called QJ-J in that version, so you might have to delete and re-add the device once to make it work.
