### ISSUE TITLE
[Bug]: Error adding entities for domain sensor with platform ble_monitor

### ISSUE THREAD

**Issue by jameson21** [custom-components/ble_monitor#825]
### What happened?

After update Home Assistant from 2022.3.6 to 2022.4.1 disappeared (state is "unavailable") entities:
- "battery", "rssi" for the LYWSDCGQ
- "battery", "voltage", "rssi" for the LYWSD03MMC.
Removing and reconnecting devices did not solve the problem.

Sensors "temperature", "humidity" for both devices are displayed normally

Note: with the ble_monitor component I use only two devices: LYWSDCGQ, LYWSD03MMC

### Sensor type

LYWSDCGQ, LYWSD03MMC

### Relevant log output

```shell
2022-04-10 13:55:58 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform ble_monitor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
entry = entity_registry.async_get_or_create(
File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
return self.async_update_entity(
File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance
2022-04-10 13:55:59 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up ble_monitor platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
entry = entity_registry.async_get_or_create(
File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
return self.async_update_entity(
File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance
2022-04-10 13:55:59 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform ble_monitor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
entry = entity_registry.async_get_or_create(
File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 383, in async_get_or_create
raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance
```

**Comment by Ernst79** [comment]
I can’t reproduce your issue. 

These sensors have the `EntityCategory.DIAGNOSTIC`. But this is still available in the latest HA version. 

https://github.com/home-assistant/core/blob/8fe9e364e10cb76461fe81d654c64d72c228d8ae/homeassistant/helpers/entity.py#L201

I also updated HA, but I’m not seeing any error, like you have.

**Comment by jameson21** [comment]
At the time of update HA, BLE monitor was version 6.4.4.
After update HA, the "battery", "voltage", "rssi" sensors disappeared. I updated the BLE monitor to the latest version, but that didn't work.

**Comment by jameson21** [comment]
This is how available and unavailable entities are now displayed in Developer Tools:

- sensor.ht2_ble_b_a4xxxxxx35

unavailable

restored: true
state_class: measurement
device_class: battery
friendly_name: Xiaomi HT2 BLE Battery
supported_features: 0
unit_of_measurement: % 


- sensor.ht2_ble_h_a4xxxxxx35

72

state_class: measurement
sensor type: LYWSD03MMC
mac address: A4:XX:XX:XX:XX:35
last packet id: 226
firmware: Xiaomi (MiBeacon V5 encrypted)
last mean of: 1
median: 72
mean: 72
rssi: -65
battery_level: 100
unit_of_measurement: %
device_class: humidity
friendly_name: Xiaomi HT2 BLE Humidity

**Comment by Ernst79** [comment]
6.4.4 is a very old version. Try a full restart after the update first. Do you get the same errors after the restart?

**Comment by jameson21** [comment]
Yes I have restarted HA and host many times, but that didn't work. I get the same errors after the restart

**Comment by Ernst79** [comment]
Hmmm, very strange. Can’t reproduce your issue, so it is hard to figure out what is wrong. Are you absolutely sure that HA is updated to 2022.4, as I can only explain the errors when you have a very old HA version.

**Comment by Ernst79** [comment]
I would try to remove BLE monitor and reinstall it.

**Comment by jameson21** [comment]
Completely uninstalled BLE Monitor, then restarted the instance, installed BLE Monitor (I use manual installation) and restarted the instance again. All sensors are working. Thank you!
I did all this on the backup HASS. The main HASS has not been updated yet. And now it’s not clear to me, was it an accidental glitch, or with the installed BLE monitor version 6.4.4 and updating the HASS from version 2022.3.6 to version 2022.4.1, should this have happened?

**Comment by Ernst79** [comment]
To be honest, I have no idea what went wrong. I think it is a combination of some deprecated things in HA 2022.4 with the old BLE monitor version. But not sure why it didn’t work after you had updated the first time. But glad it is solved now.
