### ISSUE TITLE
[New Sensor]: Govee H5184 and H5198 Smart Meat Thermometer

### ISSUE THREAD

**Issue by LunkwillAndFook** [custom-components/ble_monitor#946]
### Sensor Description

Govee Meat Thermometer H5184 (4 

### Additional information

Square body with 4 probes. 

https://us.govee.com/products/govee-bluetooth-meat-thermometer

### BLE advertisements

```shell
Device Name: Govee_H5184_5840
Device Address: CD:31:30:30:58:40

Services:--------------------------
GAP (00001800-0000-1000-8000-00805f9b34fb)
Device Name (00002a00-0000-1000-8000-00805f9b34fb)
Appearance (00002a01-0000-1000-8000-00805f9b34fb)
Peripheral Preferred Connection Parameters (00002a04-0000-1000-8000-00805f9b34fb)
Unknown characteristic (00002ac9-0000-1000-8000-00805f9b34fb)


GATT (00001801-0000-1000-8000-00805f9b34fb)
Service Changed (00002a05-0000-1000-8000-00805f9b34fb)


Unknown service (494e5445-4c4c-495f-524f-434b535f4857)
Unknown characteristic (494e5445-4c4c-495f-524f-434b535f2011)
Unknown characteristic (494e5445-4c4c-495f-524f-434b535f2012)
Unknown characteristic (494e5445-4c4c-495f-524f-434b535f2013)


Unknown service (02f00000-0000-0000-0000-00000000fe00)
Unknown characteristic (02f00000-0000-0000-0000-00000000ff03)
Unknown characteristic (02f00000-0000-0000-0000-00000000ff02)
Unknown characteristic (02f00000-0000-0000-0000-00000000ff00)
Unknown characteristic (02f00000-0000-0000-0000-00000000ff01)
```

**Comment by Ernst79** [comment]
Can you postpone ble advertisement as well. 

See https://custom-components.github.io/ble_monitor/sensor_request

**Comment by LunkwillAndFook** [comment]
![Screenshot_20220730-133732_Bluetooth LE Scanner](https://user-images.githubusercontent.com/8645580/181935201-7b48a3eb-6c63-4130-8616-64adf4c31861.jpg)

![Screenshot_20220730-133741_Bluetooth LE Scanner](https://user-images.githubusercontent.com/8645580/181935209-9aca054d-586b-48cf-ae93-5eada897340d.jpg)

**Comment by Ernst79** [comment]
Yes, it is. But it looks like this govee is using the iBeacon (Apple) format. That is not what i would have expected. Can you get some more of these, along with the measured data (temperature, ....)

**Comment by Ernst79** [comment]
Note to myself: https://github.com/Bluetooth-Devices/govee-ble/pull/29

**Comment by LunkwillAndFook** [comment]
@Ernst79 Apologies for not getting back to this. I should have some downtime over the holiday to do some more captures at different temperatures.

**Comment by NightShaman** [comment]
I was going to open a new request for the Govee 5198 4 probe  meat thermometer. 

Then I noticed I got the same information as above for it. Even has the iBeacon format. 

I will upload some screen shots. The current temp on probe 1 is 73F

**Comment by NightShaman** [comment]
![Screenshot_20221224_212836_Bluetooth LE Scanner.jpg](https://user-images.githubusercontent.com/12952292/209456138-46cca8c3-ad78-4d7e-a197-b7a7288c229e.jpg)

![Screenshot_20221224_212844_Bluetooth LE Scanner.jpg](https://user-images.githubusercontent.com/12952292/209456141-b54fc140-c4e5-454a-8d6e-2330a330195d.jpg)

**Comment by NightShaman** [comment]
Here is 93 F 

![Screenshot_20221224_213437_Bluetooth LE Scanner.jpg](https://user-images.githubusercontent.com/12952292/209456179-e9392cf9-a6b0-4e51-a99a-19257c86f592.jpg)

![Screenshot_20221224_213442_Bluetooth LE Scanner.jpg](https://user-images.githubusercontent.com/12952292/209456182-743bfff3-3e5b-40c7-9051-5c51b0a57d6c.jpg)

**Comment by NightShaman** [comment]
Probe 2 79F

![Screenshot_20221224_213718_Bluetooth LE Scanner.jpg](https://user-images.githubusercontent.com/12952292/209456219-5abd05ef-f4fe-49f4-9de7-3f552d28f363.jpg)

**Comment by NightShaman** [comment]
Port 3 
91F

![Screenshot_20221224_213908_Bluetooth LE Scanner.jpg](https://user-images.githubusercontent.com/12952292/209456241-a79a804b-3899-4968-899b-5008feaf2d66.jpg)

**Comment by NightShaman** [comment]
Port 4
76F

![Screenshot_20221224_214056_Bluetooth LE Scanner.jpg](https://user-images.githubusercontent.com/12952292/209456272-d93f7f81-c813-4abc-91e9-d05d8bce650a.jpg)

**Comment by NightShaman** [comment]
Hope that helps. If you need anything else let me know.

**Comment by Ernst79** [comment]
Thanks, can this be correct?

```
{'firmware': 'Govee', 'temperature probe 1': 0.0, 'temperature probe 2': 74.0, 'temperature probe 3': 0.0, 'temperature probe 4': 63.0, 'rssi': -59, 'mac': 'C6313030226C', 'type': 'H5198', 'packet': 'no packet id', 'data': True}
```

**Comment by Ernst79** [comment]
I think the H5198 will the same format as the H5184. Can you both test with 11.4.0-beta (enable beta releases in HACS). I'm pretty convinced about the H5184, not 100% sure about the H5198

**Comment by NightShaman** [comment]
Possible on the alarm, I do not believe I had an alarm set that low. The lowest I set it was 95. To let me know the smoker went out... Testing 11.4.0-beta, It found the device, and not an iBeacon so progress :) 

After 8 min still unknown for temp, I set the alarm on the first one to 95. and that was unknown as well.

**Comment by NightShaman** [comment]
This was probe 1 @ 73 with alarm set if it goes below 95

![Screenshot_20230109_064627_Bluetooth LE Scanner.jpg](https://user-images.githubusercontent.com/12952292/211311504-1f7be510-67e2-4186-97c1-c3d172541d1d.jpg)![Screenshot_20230109_064633_Bluetooth LE Scanner.jpg](https://user-images.githubusercontent.com/12952292/211311523-e12ab0fa-84b2-474f-b605-a7b98f23deb7.jpg)

**Comment by Ernst79** [comment]
A little bit of background, how I have programmed it in the beta version. When looking at your data, I printed the part that starts with `17ff....`, which is the manufacturer specific data. 

```
# 17ff3022 6c01000101c0 01 0f ffff   1ce8    ffff ffff   189c    ffff 1aff4c000215494e54454c4c495f524f434b535f48575075f2ff0c00000000
# 17ff3022 6c01000101b5 02 0f ffff   ffff    ffff ffff   ffff    ffff 1aff4c000215494e54454c4c495f524f434b535f48575075f2ff0c00000000
#     uuid              id    temp 1 alarm 1 ---- temp 2 alarm 2 ---- |------------iBeacon package---------------------------------|
```

The `id` is `01` for probe 1 and 2. If the `id` is `02`, than it reports probe 3 and 4 (that is how the 5184 works, looks the same here). 
As you can see, I left 2x2 bytes unused, not sure what data is in these parts. If you can make some more screenshots for which you write down which sensor is connected, which alarm temperature is set and which temperature is measured, I can probably find out how it works. But keep an eye on the `id`, that it corresponds to what you want to have measured (`01` for probe 1 and 2. `02` for probe 3 and 4)

**Comment by NightShaman** [comment]
Ok I will work on that. I was out of town this week so was unable to. 
I will get more readings this weekend. I will try to do each probe with a low alarm, high alarm and no alarm set. 
And all 4 plugged in at the same time. to see if that helps.

**Comment by NightShaman** [comment]
Sorry weekend was crazy pants. I plugged in all 4 got them to different Temps. No alerts set figured a good place to start. 

![20230117_200227.jpg](https://user-images.githubusercontent.com/12952292/213063207-65373958-0026-4fdc-8228-2736432ddceb.jpg)

![Screenshot_20230117_200221_Bluetooth LE Scanner.jpg](https://user-images.githubusercontent.com/12952292/213063235-238cf325-cbae-43c3-bfdd-cee36c6dbfe6.jpg)

**Comment by Ernst79** [comment]
```
#     comp_id              ?? ??    temp a alarm a ---- temp b alarm b ----
---------------------------------------------------------------------------
# 17ff  3022    6c01000101 b5 02 0f ffff   ffff   ffff   ffff   ffff   ffff (probe 1 and 2 not connected)
#
#
# 17ff  3022    6c01000101 bf 42 0f 0ce4   ffff   ffff   ffff   ffff   0dac (probe 3 = 91F)
#                                   33.0C                              35.0C
#                                   =91F                               =95F
# 17ff  3022    6c01000101 c0 01 0f ffff   1ce8   ffff   ffff   189c   0dac (probe 1 and 2 not connected)
#                                          74.0C                63.0C
#                                          =165F                =145F
# 17ff  3022    6c01000101 b5 02 0f ffff   ffff   ffff   ffff   ffff   ffff (probe 1 and 2 not connected)
#
#
# 17ff  3022    6c01000101 c0 41 0f 0ce4   1ce8   ffff   ffff   189c   ffff (probe 1 = 93F, or perhaps probe 3 = 91F???)
#                                   33.0C  74.0C                63.0C
#                                   =91F   =165F                =145F
# 17ff  3022    6c01000101 b2 c2 0f 0af0   ffff   ffff   0e74   ffff   ffff (probe 3 = 82F, probe 4 = 99F)
#                                   28.0C                37.0C
#                                   =82F                 =99F
```

I'm able to find the temperatures just fine, but the problem is that I can't figure out when it reports probe 1+2 and when probe 3+4. The other sensors have a byte that is 01 or 02 I thought the second ?? column was used for this, but it turns out it has more different values. Can't see the logic yet.  

Do you have the Bluetooth integration installed in HA. if so, can you make a longer log in HA, by enabling debug logging in HA for the Bluetooth integration. Please make a printscreen of the connected sensors temperatures.

**Comment by NightShaman** [comment]
I do I think when I tried before It wasn't logging. Probably a me issue. I will try again once I get a chance.

**Comment by NightShaman** [comment]
Not sure if I messed up and should have stayed on 11.4.0 beta, I have a habit of just updating. Now when it connected it goes back to iBeacon. 
I don't see the option for that beta anymore. 

Was able to find the Set debug I will attach. 
But as it went back to iBeacon I can tell you the temps. 
Probe 1: 84
Probe 2: 73
Probe 3: 97
Probe 4: 79

Not sure if it makes a difference or not in what you are looking at but this model also has WiFi 

[home-assistant_2023-01-22T16-09-06.297Z.log](https://github.com/custom-components/ble_monitor/files/10474881/home-assistant_2023-01-22T16-09-06.297Z.log)

**Comment by Ernst79** [comment]
You should have stayed on that beta. I'll create a new one,

**Comment by Ernst79** [comment]
I just released 11.5.0-beta, which has the Govee H5184 and H5198 code. 

For the H5198, you now only have to enable debug logging  for BLE monitor (at debug level). I added a line of code that will make the logs.

**Comment by NightShaman** [comment]
Ok will make sure not to update again until we get this down. No matter what yells at me.. 

Installing now. Should have some data soon

**Comment by NightShaman** [comment]
Hoping this helps. 
HA shows Unknown for all temps. 

Current Temps with no alarms is 
Probe 1: 86
Probe 2: 75
Probe 3: 97
Probe 4: 72

![image](https://user-images.githubusercontent.com/12952292/213934557-fcbec7c3-32c4-4cfc-ad36-bc5d9ad0c72d.png)

[home-assistant_2023-01-22T18-56-12.401Z.log](https://github.com/custom-components/ble_monitor/files/10475229/home-assistant_2023-01-22T18-56-12.401Z.log)

**Comment by Ernst79** [comment]
This is the right info I need. I collected some of the data. Temperature is clear. Now I need to figure out how it determines which sensor is broadcasting. I can see it is switching between probe 1+2 and probe 3+4, but I don't see the logic how you can see which is which. Can you make a really long log, like 15 minutes long log? 

```
#     comp_id              ?? ??    temp a alarm a ---- temp b alarm b ----   temp C  temp F  temp C  temp F    probe
---------------------------------------------------------------------------      probe a          probe b
# 17ff  3022    6c01000101 b5 02 0f ffff   ffff   ffff   ffff   ffff   ffff   not connected    not connected   1 and 2
# 17ff  3022    6c01000101 b5 02 0f ffff   ffff   ffff   ffff   ffff   ffff   not connected    not connected   1 and 2
# 17ff  3022    6c01000101 a6 c1 0f 0bb8   ffff   ffff   0960   ffff   ffff   30 C = 86 F      24 C = 75 F     1 and 2
# 17ff  3022    6c01000101 a5 c1 0f 0bb8   ffff   ffff   0960   ffff   ffff   30 C = 86 F      24 C = 75 F     1 and 2
# 17ff  3022    6c01000101 bf 42 0f 0ce4   ffff   ffff   ffff   ffff   0dac   33 C = 91 F      alarm set       1 and 2
# 17ff  3022    6c01000101 c0 01 0f ffff   1ce8   ffff   ffff   189c   0dac   alarm set        alarm set       1 and 2

# 17ff  3022    6c01000101 c0 41 0f 0ce4   1ce8   ffff   ffff   189c   ffff   33 C = 91 F      alarm set       1 and 2 or 3 and 4

# 17ff  3022    6c01000101 b2 c2 0f 0af0   ffff   ffff   0e74   ffff   ffff   28 C = 82 F      37 C = 99 F     3 and 4 
# 17ff  3022    6c01000101 a6 c2 0f 0e10   ffff   ffff   0898   ffff   ffff   36 C = 97 F      22 C = 72 F     3 and 4
# 17ff  3022    6c01000101 a5 c2 0f 0e10   ffff   ffff   0898   ffff   ffff   36 C = 97 F      22 C = 72 F     3 and 4
```

**Comment by NightShaman** [comment]
Ok think I got it all 

[home-assistant_2023-01-22T20-38-41.026Z.log](https://github.com/custom-components/ble_monitor/files/10475449/home-assistant_2023-01-22T20-38-41.026Z.log)

**Comment by NightShaman** [comment]
I know 1st order of business is sensors. When looking through all the data, are you able to see battery level as well?

**Comment by Ernst79** [comment]
Thanks, I’ll check the data tomorrow. I’ll also look for battery info

**Comment by Ernst79** [comment]
In your last data set, I have the following

`c1` = probe 1+2
`c2` = probe 3+4
`41` = probe 1
`81` = probe 2
`42` = probe 3
`82` = probe 4

There is no relation with the alarm (no need to BTW). 

From the earlier messages, we have 
`01` = probe 1+2 not connected
`02` = probe 3+4 not connected

I think we have all the info we need. The only thing I don't know is what the 3rd temperature is for each probe. We have 6 values: temperature, alarm, ......., temperature, alarm, ........ . No idea what the 3rd value is. 

I'll prepare an update for you tonight

**Comment by Ernst79** [comment]
11.5.0 has been released as final. I think it should work now

**Comment by NightShaman** [comment]
Appreciate all the work! 

Looks like it did with the beta when discovered. 

![image](https://user-images.githubusercontent.com/12952292/214836704-6ccd8530-a997-4844-8d1e-bd5ada1998af.png)

**Comment by Ernst79** [comment]
It's all `unknown`? Did you install the final version 11.5.0?

**Comment by NightShaman** [comment]
I did, I even went as far as to delete it from HACS and re-install it, no beta selected. 

It's showing like it did in beta, 2 alarms, 3 probes. all unknown

**Comment by NightShaman** [comment]
not sure if this may have something to do with it. 

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/ble_monitor/sensor.py:151
Integration: Passive BLE monitor (documentation, issues)
First occurred: 8:37:52 PM (1 occurrences)
Last logged: 8:37:52 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/ble_monitor/sensor.py", line 210, in async_run
    sensors = await async_add_sensor(
  File "/config/custom_components/ble_monitor/sensor.py", line 151, in async_add_sensor
    description = [item for item in SENSOR_TYPES if item.key is measurement][0]
IndexError: list index out of range

**Comment by Ernst79** [comment]
An, thanks. I see I forgot to add the alarms for sensor 3 and 4 in SENSOR_TYPES. That is why it stops after two alarms. I’ll fix it.

**Comment by Ernst79** [comment]
Should be fixed in 11.5.1.

**Comment by NightShaman** [comment]
Now I get 4 Alarms, and 4 sensors. 
The Alarm Temps are inaccurate. 
Alarm Probe 1 Set 420 F - Shows 215.6 F
Alarm Probe 2 Set 129 F - Shows 54.0 F
Alarm Probe 3 Set 140 F - Shows 60.0 F

None of the actual Probe Temps display. 

![image](https://user-images.githubusercontent.com/12952292/215070385-3655be46-0799-4c8c-9cfa-0c9e2b6e4c00.png)

**Comment by Ernst79** [comment]
How did you set the temperature unit in the BLE monitor settings for this sensor? You should set it to **Celsius**, as the sensor sends its data in Celsius. HA will do the conversion to Fahrenheit (based on your location/HA system unit settings. 

![image](https://user-images.githubusercontent.com/24375847/215081670-d7d3cd0f-7b9d-4ffd-9852-79c487600e2e.png)

**Comment by NightShaman** [comment]
Ahh ok that makes sense there for the alarm. 

But a probe was plugged in and nothing showed up for the probe.

**Comment by NightShaman** [comment]
Ok weird checked again this evening and they all popped up. 

Looks like when no alarm or probe is attached, they default 0 C which is 32 F. 

Thanks for the work on this.

**Comment by NightShaman** [comment]
That 3rd temp, I think I figured out what that was. On this device there is a High and Low temp Alarm. The High temp alarm shows up no issus in HA, the Low temp Alarm does not show up at all.

**Comment by Ernst79** [comment]
Yes, it now defaults to 0 degrees Celsius when no probe is attached. I can change that to “unavailable” and I can add the low tamp alarm as well.

**Comment by NightShaman** [comment]
Appreciate the help on this. If you could change that to unavailable I would appreciate that.  
I think I was wrong about the low temp. Not even sure if there is a proper way to read that alarm. 
Currently if I set a low alarm. Everything goes weird. 
I had Probe 1 connected, Set the Low temp and then it reported the screenshot below. Maybe we just go back to before without the low. 

![image](https://user-images.githubusercontent.com/12952292/216494560-da5495a3-6b6e-47cd-afc5-247c4622477d.png)

**Comment by Ernst79** [comment]
I found the issue with the 4th low alarm, I made a typo. I used the 3rd instead. Will fix that in 11.6.2. Letting the sensors go to unavailable is a bit harder. Will do that later.

**Comment by NightShaman** [comment]
Whatever you could do I appreciate it.

**Comment by loopy321** [comment]
Thanks for your efforts on this!  I have the H5184 and noticed that it reports 0C  when a probe is not connected.  

My data looks like the following when only probe-1 is connected:

```
2023-04-12 09:57:26.741 DEBUG (MainThread) [custom_components.ble_monitor.sensor] Data measuring sensor received: {'firmware': 'Govee', 'temperature probe 1': 23.0, 'temperature alarm probe 1': 0.0, 'temperature probe 2': 0.0, 'temperature alarm probe 2': 0.0, 'rssi': -60, 'mac': 'C53732321233', 'type': 'H5184', 'packet': 'no packet id', 'data': True}
2023-04-12 09:57:29.755 DEBUG (MainThread) [homeassistant.components.bluetooth.manager] hci0 (00:E0:4C:C1:17:03) [connectable]: C5:37:32:32:12:33 AdvertisementData(manufacturer_data={4658: b'3\x01\x00\x01\x01\xe4\x02\x06\xff\xff\xff\xff\x06\xff\xff\xff\xff'}, service_uuids=['00008451-0000-1000-8000-00805f9b34fb'], rssi=-56) match: set()
2023-04-12 09:57:33.574 DEBUG (MainThread) [custom_components.ble_monitor.sensor] Data measuring sensor received: {'firmware': 'Govee', 'temperature probe 3': 0.0, 'temperature alarm probe 3': 0.0, 'temperature probe 4': 0.0, 'temperature alarm probe 4': 0.0, 'rssi': -60, 'mac': 'C53732321233', 'type': 'H5184', 'packet': 'no packet id', 'data': True}
```
Maybe this helps to identify the bits for disconnected?

**Comment by loopy321** [comment]
And with all four probes connected:

```
2023-04-12 10:21:05.999 DEBUG (MainThread) [homeassistant.components.bluetooth.manager] hci0 (00:E0:4C:C1:17:03) [connectable]: C5:37:32:32:12:33 AdvertisementData(manufacturer_data={4658: b'3\x01\x00\x01\x01\xe4\x02\x86\x08\xfc\xff\xff\x86\x08\xfc\xff\xff', 76: b'\x02\x15INTELLI_ROCKS_HWPu\xf2\xff\x0c'}, service_uuids=['00008451-0000-1000-8000-00805f9b34fb'], rssi=-62) match: set()

2023-04-12 10:21:35.192 DEBUG (MainThread) [custom_components.ble_monitor.sensor] Data measuring sensor received: {'firmware': 'Govee', 'temperature probe 3': 23.0, 'temperature alarm probe 3': 0.0, 'temperature probe 4': 23.0, 'temperature alarm probe 4': 0.0, 'rssi': -60, 'mac': 'C53732321233', 'type': 'H5184', 'packet': 'no packet id', 'data': True}

2023-04-12 10:22:44.393 DEBUG (MainThread) [custom_components.ble_monitor.sensor] Data measuring sensor received: {'firmware': 'Govee', 'temperature probe 1': 23.0, 'temperature alarm probe 1': 0.0, 'temperature probe 2': 24.0, 'temperature alarm probe 2': 0.0, 'rssi': -58, 'mac': 'C53732321233', 'type': 'H5184', 'packet': 'no packet id', 'data': True}

```
